/**
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * Generated by scripts/generate-legal-sources-meta.ts from the
 * legal-sources corpus barrel. Regenerate after any corpus change:
 *
 *   npx tsx scripts/generate-legal-sources-meta.ts
 *
 * Guarded by src/data/legal-sources/meta-drift.test.ts (CI fails if
 * this file is stale). Client-safe: contains ONLY light metadata, no
 * key_provisions / scope texts.
 *
 * SPDX-License-Identifier: LicenseRef-Caelex-Proprietary
 */

import type { CorpusStats, JurisdictionMetaRecord } from "./types";

/** Top-level corpus inventory counts. */
export const CORPUS_STATS: CorpusStats = {
  sources: 1117,
  authorities: 424,
  jurisdictions: 67,
};

/** All catalogued jurisdiction codes (getAvailableJurisdictions order). */
export const JURISDICTION_CODES: readonly string[] = [
  "INT",
  "EU",
  "DE",
  "FR",
  "UK",
  "IT",
  "LU",
  "NL",
  "BE",
  "ES",
  "NO",
  "SE",
  "FI",
  "DK",
  "AT",
  "CH",
  "PT",
  "IE",
  "GR",
  "CZ",
  "PL",
  "EE",
  "RO",
  "HU",
  "SI",
  "LV",
  "LT",
  "SK",
  "HR",
  "TR",
  "IS",
  "LI",
  "US",
  "NZ",
  "JP",
  "IN",
  "AU",
  "CA",
  "AE",
  "KR",
  "IL",
  "CN",
  "RU",
  "BR",
  "ZA",
  "SG",
  "ID",
  "PH",
  "SA",
  "EG",
  "AR",
  "MX",
  "TW",
  "KE",
  "CL",
  "NG",
  "VN",
  "MA",
  "TH",
  "PK",
  "DZ",
  "BD",
  "IR",
  "KZ",
  "KP",
  "MN",
  "CO",
];

/** Distinct `source.jurisdiction` values across ALL_SOURCES, sorted. */
export const SOURCE_JURISDICTION_CODES: readonly string[] = [
  "AE",
  "AR",
  "AT",
  "AU",
  "BD",
  "BE",
  "BR",
  "CA",
  "CH",
  "CL",
  "CN",
  "CO",
  "CZ",
  "DE",
  "DK",
  "DZ",
  "EE",
  "EG",
  "ES",
  "EU",
  "FI",
  "FR",
  "GR",
  "HR",
  "HU",
  "ID",
  "IE",
  "IL",
  "IN",
  "INT",
  "IR",
  "IS",
  "IT",
  "JP",
  "KE",
  "KP",
  "KR",
  "KZ",
  "LI",
  "LT",
  "LU",
  "LV",
  "MA",
  "MN",
  "MX",
  "NG",
  "NL",
  "NO",
  "NZ",
  "PH",
  "PK",
  "PL",
  "PT",
  "RO",
  "RU",
  "SA",
  "SE",
  "SG",
  "SI",
  "SK",
  "TH",
  "TR",
  "TW",
  "UK",
  "US",
  "VN",
  "ZA",
];

/** Per-jurisdiction aggregates (counts, treaty flags, quick-ref data). */
export const JURISDICTION_META: readonly JurisdictionMetaRecord[] = [
  {
    code: "INT",
    sourceCount: 169,
    authorityCount: 3,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: [
      "liability",
      "debris_mitigation",
      "frequency_spectrum",
    ],
    authoritiesPreview: [
      {
        id: "INT-UNOOSA",
        abbreviation: "UNOOSA",
      },
      {
        id: "INT-ITU",
        abbreviation: "ITU",
      },
      {
        id: "INT-COPUOS",
        abbreviation: "COPUOS",
      },
    ],
  },
  {
    code: "EU",
    sourceCount: 40,
    authorityCount: 3,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["cybersecurity", "licensing", "debris_mitigation"],
    authoritiesPreview: [
      {
        id: "EU-EC",
        abbreviation: "EC",
      },
      {
        id: "EU-EUSPA",
        abbreviation: "EUSPA",
      },
      {
        id: "EU-ENISA",
        abbreviation: "ENISA",
      },
    ],
  },
  {
    code: "DE",
    sourceCount: 79,
    authorityCount: 11,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "cybersecurity", "liability"],
    authoritiesPreview: [
      {
        id: "DE-BMWK",
        abbreviation: "BMWE",
      },
      {
        id: "DE-BMFTR",
        abbreviation: "BMFTR",
      },
      {
        id: "DE-DLR",
        abbreviation: "DLR",
      },
    ],
  },
  {
    code: "FR",
    sourceCount: 70,
    authorityCount: 15,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "FR-CNES",
        abbreviation: "CNES",
      },
      {
        id: "FR-CDE",
        abbreviation: "CDE",
      },
      {
        id: "FR-DGA",
        abbreviation: "DGA",
      },
    ],
  },
  {
    code: "UK",
    sourceCount: 71,
    authorityCount: 14,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "liability", "registration"],
    authoritiesPreview: [
      {
        id: "UK-CAA",
        abbreviation: "CAA",
      },
      {
        id: "UK-UKSA",
        abbreviation: "UKSA",
      },
      {
        id: "UK-OFCOM",
        abbreviation: "Ofcom",
      },
    ],
  },
  {
    code: "IT",
    sourceCount: 65,
    authorityCount: 14,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "cybersecurity"],
    authoritiesPreview: [
      {
        id: "IT-PDC",
        abbreviation: "PdCM",
      },
      {
        id: "IT-ASI",
        abbreviation: "ASI",
      },
      {
        id: "IT-COMINT",
        abbreviation: "COMINT",
      },
    ],
  },
  {
    code: "LU",
    sourceCount: 54,
    authorityCount: 11,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "LU-LSA",
        abbreviation: "LSA",
      },
      {
        id: "LU-MECO",
        abbreviation: "MECO",
      },
      {
        id: "LU-ILR",
        abbreviation: "ILR",
      },
    ],
  },
  {
    code: "NL",
    sourceCount: 58,
    authorityCount: 15,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: true,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "NL-NSO",
        abbreviation: "NSO",
      },
      {
        id: "NL-EZK",
        abbreviation: "EZK",
      },
      {
        id: "NL-RDI",
        abbreviation: "RDI",
      },
    ],
  },
  {
    code: "BE",
    sourceCount: 58,
    authorityCount: 15,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: true,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "BE-BELSPO",
        abbreviation: "BELSPO",
      },
      {
        id: "BE-MINISTER-SCIENCE",
        abbreviation: "Min. Science",
      },
      {
        id: "BE-MOD",
        abbreviation: "MOD",
      },
    ],
  },
  {
    code: "ES",
    sourceCount: 54,
    authorityCount: 13,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "ES-AEE",
        abbreviation: "AEE",
      },
      {
        id: "ES-INTA",
        abbreviation: "INTA",
      },
      {
        id: "ES-CDTI",
        abbreviation: "CDTI",
      },
    ],
  },
  {
    code: "NO",
    sourceCount: 42,
    authorityCount: 13,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "NO-NOSA",
        abbreviation: "NOSA",
      },
      {
        id: "NO-CAA",
        abbreviation: "CAA",
      },
      {
        id: "NO-NFD",
        abbreviation: "NFD",
      },
    ],
  },
  {
    code: "SE",
    sourceCount: 48,
    authorityCount: 14,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "SE-SNSA",
        abbreviation: "SNSA",
      },
      {
        id: "SE-SSC",
        abbreviation: "SSC",
      },
      {
        id: "SE-PTS",
        abbreviation: "PTS",
      },
    ],
  },
  {
    code: "FI",
    sourceCount: 46,
    authorityCount: 13,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "FI-TEM",
        abbreviation: "TEM",
      },
      {
        id: "FI-TRAFICOM",
        abbreviation: "Traficom",
      },
      {
        id: "FI-UM",
        abbreviation: "UM",
      },
    ],
  },
  {
    code: "DK",
    sourceCount: 46,
    authorityCount: 11,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "DK-UFM",
        abbreviation: "UFM",
      },
      {
        id: "DK-UFST",
        abbreviation: "UFST",
      },
      {
        id: "DK-DTU-SPACE",
        abbreviation: "DTU Space",
      },
    ],
  },
  {
    code: "AT",
    sourceCount: 47,
    authorityCount: 10,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: true,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "AT-BMIMI",
        abbreviation: "BMIMI",
      },
      {
        id: "AT-FFG",
        abbreviation: "FFG/ALR",
      },
      {
        id: "AT-RTR",
        abbreviation: "RTR",
      },
    ],
  },
  {
    code: "CH",
    sourceCount: 36,
    authorityCount: 10,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "CH-SSO",
        abbreviation: "SSO/SBFI",
      },
      {
        id: "CH-OFCOM",
        abbreviation: "OFCOM/BAKOM",
      },
      {
        id: "CH-SECO",
        abbreviation: "SECO",
      },
    ],
  },
  {
    code: "PT",
    sourceCount: 44,
    authorityCount: 10,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "PT-ANACOM",
        abbreviation: "ANACOM",
      },
      {
        id: "PT-PTSPACE",
        abbreviation: "Portugal Space",
      },
      {
        id: "PT-MECI",
        abbreviation: "MECI",
      },
    ],
  },
  {
    code: "IE",
    sourceCount: 39,
    authorityCount: 8,
    treaties: {
      ost: true,
      liability: true,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "IE-DETE",
        abbreviation: "DETE",
      },
      {
        id: "IE-EI",
        abbreviation: "EI",
      },
      {
        id: "IE-COMREG",
        abbreviation: "ComReg",
      },
    ],
  },
  {
    code: "GR",
    sourceCount: 44,
    authorityCount: 8,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "GR-HSC",
        abbreviation: "HSC/ΕΛΚΕΔ",
      },
      {
        id: "GR-MINDIGITAL",
        abbreviation: "ΓΓΤΤ",
      },
      {
        id: "GR-EETT",
        abbreviation: "EETT",
      },
    ],
  },
  {
    code: "CZ",
    sourceCount: 46,
    authorityCount: 9,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "CZ-MOT",
        abbreviation: "MD/CSA",
      },
      {
        id: "CZ-CTU",
        abbreviation: "ČTÚ",
      },
      {
        id: "CZ-MPO",
        abbreviation: "MPO",
      },
    ],
  },
  {
    code: "PL",
    sourceCount: 46,
    authorityCount: 10,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "PL-POLSA",
        abbreviation: "POLSA",
      },
      {
        id: "PL-MFIG",
        abbreviation: "MFiG",
      },
      {
        id: "PL-MON",
        abbreviation: "MON/ARGUS",
      },
    ],
  },
  {
    code: "EE",
    sourceCount: 11,
    authorityCount: 6,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["cybersecurity", "licensing", "registration"],
    authoritiesPreview: [
      {
        id: "EE-MKM",
        abbreviation: "MKM",
      },
      {
        id: "EE-TTJA",
        abbreviation: "TTJA",
      },
      {
        id: "EE-RIA",
        abbreviation: "RIA",
      },
    ],
  },
  {
    code: "RO",
    sourceCount: 9,
    authorityCount: 6,
    treaties: {
      ost: true,
      liability: true,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["cybersecurity", "licensing", "liability"],
    authoritiesPreview: [
      {
        id: "RO-ROSA",
        abbreviation: "ROSA",
      },
      {
        id: "RO-ANCOM",
        abbreviation: "ANCOM",
      },
      {
        id: "RO-MCID",
        abbreviation: "MCID",
      },
    ],
  },
  {
    code: "HU",
    sourceCount: 10,
    authorityCount: 6,
    treaties: {
      ost: true,
      liability: true,
      registration: false,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "cybersecurity", "liability"],
    authoritiesPreview: [
      {
        id: "HU-HSO",
        abbreviation: "HSO",
      },
      {
        id: "HU-NMHH",
        abbreviation: "NMHH",
      },
      {
        id: "HU-KKM",
        abbreviation: "KKM",
      },
    ],
  },
  {
    code: "SI",
    sourceCount: 10,
    authorityCount: 6,
    treaties: {
      ost: true,
      liability: true,
      registration: false,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "cybersecurity", "liability"],
    authoritiesPreview: [
      {
        id: "SI-MGTS",
        abbreviation: "MGTS",
      },
      {
        id: "SI-AKOS",
        abbreviation: "AKOS",
      },
      {
        id: "SI-MZZEU",
        abbreviation: "MZZ",
      },
    ],
  },
  {
    code: "LV",
    sourceCount: 9,
    authorityCount: 6,
    treaties: {
      ost: true,
      liability: true,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["cybersecurity", "licensing", "liability"],
    authoritiesPreview: [
      {
        id: "LV-IZM",
        abbreviation: "IZM",
      },
      {
        id: "LV-EM",
        abbreviation: "EM",
      },
      {
        id: "LV-VASESD",
        abbreviation: "VAS ESD",
      },
    ],
  },
  {
    code: "LT",
    sourceCount: 10,
    authorityCount: 6,
    treaties: {
      ost: true,
      liability: true,
      registration: false,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "cybersecurity", "liability"],
    authoritiesPreview: [
      {
        id: "LT-EIM",
        abbreviation: "EIM",
      },
      {
        id: "LT-RRT",
        abbreviation: "RRT",
      },
      {
        id: "LT-URM",
        abbreviation: "URM",
      },
    ],
  },
  {
    code: "SK",
    sourceCount: 9,
    authorityCount: 6,
    treaties: {
      ost: true,
      liability: true,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["cybersecurity", "licensing", "liability"],
    authoritiesPreview: [
      {
        id: "SK-MSVVAM",
        abbreviation: "MŠVVaM",
      },
      {
        id: "SK-RU",
        abbreviation: "RÚ",
      },
      {
        id: "SK-MZV",
        abbreviation: "MZVEZ",
      },
    ],
  },
  {
    code: "HR",
    sourceCount: 9,
    authorityCount: 6,
    treaties: {
      ost: true,
      liability: true,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["cybersecurity", "licensing", "liability"],
    authoritiesPreview: [
      {
        id: "HR-MZO",
        abbreviation: "MZO",
      },
      {
        id: "HR-HAKOM",
        abbreviation: "HAKOM",
      },
      {
        id: "HR-MVEP",
        abbreviation: "MVEP",
      },
    ],
  },
  {
    code: "TR",
    sourceCount: 6,
    authorityCount: 6,
    treaties: {
      ost: true,
      liability: true,
      registration: false,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "liability", "registration"],
    authoritiesPreview: [
      {
        id: "TR-TUA",
        abbreviation: "TUA",
      },
      {
        id: "TR-BTK",
        abbreviation: "BTK",
      },
      {
        id: "TR-DIS",
        abbreviation: "MFA",
      },
    ],
  },
  {
    code: "IS",
    sourceCount: 5,
    authorityCount: 4,
    treaties: {
      ost: true,
      liability: true,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "liability", "registration"],
    authoritiesPreview: [
      {
        id: "IS-HVIN",
        abbreviation: "HVIN",
      },
      {
        id: "IS-FJS",
        abbreviation: "FJS",
      },
      {
        id: "IS-CERTIS",
        abbreviation: "CERT-IS",
      },
    ],
  },
  {
    code: "LI",
    sourceCount: 4,
    authorityCount: 4,
    treaties: {
      ost: true,
      liability: true,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "liability", "registration"],
    authoritiesPreview: [
      {
        id: "LI-REG",
        abbreviation: "Regierung",
      },
      {
        id: "LI-AFK",
        abbreviation: "AK",
      },
      {
        id: "LI-FMA",
        abbreviation: "FMA",
      },
    ],
  },
  {
    code: "US",
    sourceCount: 67,
    authorityCount: 8,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "procurement", "debris_mitigation"],
    authoritiesPreview: [
      {
        id: "US-FAA-AST",
        abbreviation: "FAA/AST",
      },
      {
        id: "US-FCC",
        abbreviation: "FCC",
      },
      {
        id: "US-NOAA-CRSRA",
        abbreviation: "NOAA/CRSRA",
      },
    ],
  },
  {
    code: "NZ",
    sourceCount: 20,
    authorityCount: 5,
    treaties: {
      ost: true,
      liability: true,
      registration: true,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "liability", "registration"],
    authoritiesPreview: [
      {
        id: "NZ-MBIE-NZSA",
        abbreviation: "NZSA",
      },
      {
        id: "NZ-CAA",
        abbreviation: "CAA-NZ",
      },
      {
        id: "NZ-MFAT",
        abbreviation: "MFAT",
      },
    ],
  },
  {
    code: "JP",
    sourceCount: 25,
    authorityCount: 4,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "procurement", "debris_mitigation"],
    authoritiesPreview: [
      {
        id: "JP-CABINET-OFFICE",
        abbreviation: "Cabinet Office NSPO",
      },
      {
        id: "JP-METI",
        abbreviation: "METI",
      },
      {
        id: "JP-MIC",
        abbreviation: "MIC",
      },
    ],
  },
  {
    code: "IN",
    sourceCount: 28,
    authorityCount: 3,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "frequency_spectrum", "registration"],
    authoritiesPreview: [
      {
        id: "IN-SPACE",
        abbreviation: "IN-SPACe",
      },
      {
        id: "IN-DOS",
        abbreviation: "DOS",
      },
      {
        id: "IN-ISRO",
        abbreviation: "ISRO",
      },
    ],
  },
  {
    code: "AU",
    sourceCount: 25,
    authorityCount: 3,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: true,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "military_dual_use", "debris_mitigation"],
    authoritiesPreview: [
      {
        id: "AU-ASA",
        abbreviation: "ASA",
      },
      {
        id: "AU-ACMA",
        abbreviation: "ACMA",
      },
      {
        id: "AU-DEFENCE",
        abbreviation: "DEC",
      },
    ],
  },
  {
    code: "CA",
    sourceCount: 5,
    authorityCount: 3,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "liability", "data_security"],
    authoritiesPreview: [
      {
        id: "CA-CSA",
        abbreviation: "CSA / ASC",
      },
      {
        id: "CA-ISED",
        abbreviation: "ISED",
      },
      {
        id: "CA-FOREIGN-AFFAIRS",
        abbreviation: "GAC",
      },
    ],
  },
  {
    code: "AE",
    sourceCount: 8,
    authorityCount: 2,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "registration", "liability"],
    authoritiesPreview: [
      {
        id: "AE-UAESA",
        abbreviation: "UAESA",
      },
      {
        id: "AE-MBRSC",
        abbreviation: "MBRSC",
      },
    ],
  },
  {
    code: "KR",
    sourceCount: 23,
    authorityCount: 3,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["licensing", "procurement", "registration"],
    authoritiesPreview: [
      {
        id: "KR-KASA",
        abbreviation: "KASA",
      },
      {
        id: "KR-MSIT",
        abbreviation: "MSIT",
      },
      {
        id: "KR-KARI",
        abbreviation: "KARI",
      },
    ],
  },
  {
    code: "IL",
    sourceCount: 9,
    authorityCount: 3,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: [
      "fdi_screening",
      "frequency_spectrum",
      "military_dual_use",
    ],
    authoritiesPreview: [
      {
        id: "IL-ISA",
        abbreviation: "ISA",
      },
      {
        id: "IL-DECA",
        abbreviation: "DECA",
      },
      {
        id: "IL-MOC",
        abbreviation: "MOC",
      },
    ],
  },
  {
    code: "CN",
    sourceCount: 29,
    authorityCount: 9,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "liability", "fdi_screening"],
    authoritiesPreview: [
      {
        id: "CN-CNSA",
        abbreviation: "CNSA",
      },
      {
        id: "CN-SASTIND",
        abbreviation: "SASTIND",
      },
      {
        id: "CN-MIIT",
        abbreviation: "MIIT",
      },
    ],
  },
  {
    code: "RU",
    sourceCount: 21,
    authorityCount: 7,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["liability", "procurement", "licensing"],
    authoritiesPreview: [
      {
        id: "RU-ROSCOSMOS",
        abbreviation: "Roscosmos",
      },
      {
        id: "RU-FSTEC",
        abbreviation: "FSTEC",
      },
      {
        id: "RU-FSB-CRYPTO",
        abbreviation: "FSB-CLSZ",
      },
    ],
  },
  {
    code: "BR",
    sourceCount: 21,
    authorityCount: 3,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["procurement", "licensing", "export_control"],
    authoritiesPreview: [
      {
        id: "BR-AEB",
        abbreviation: "AEB",
      },
      {
        id: "BR-DECEA",
        abbreviation: "DECEA",
      },
      {
        id: "BR-ANATEL",
        abbreviation: "ANATEL",
      },
    ],
  },
  {
    code: "ZA",
    sourceCount: 16,
    authorityCount: 2,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["procurement", "military_dual_use", "fdi_screening"],
    authoritiesPreview: [
      {
        id: "ZA-SANSA",
        abbreviation: "SANSA",
      },
      {
        id: "ZA-SACOUNCIL",
        abbreviation: "SACSA",
      },
    ],
  },
  {
    code: "SG",
    sourceCount: 16,
    authorityCount: 6,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["frequency_spectrum", "liability", "licensing"],
    authoritiesPreview: [
      {
        id: "SG-OSTIN",
        abbreviation: "OSTIn",
      },
      {
        id: "SG-IMDA",
        abbreviation: "IMDA",
      },
      {
        id: "SG-STCO",
        abbreviation: "STCO",
      },
    ],
  },
  {
    code: "ID",
    sourceCount: 14,
    authorityCount: 4,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "liability", "registration"],
    authoritiesPreview: [
      {
        id: "ID-BRIN",
        abbreviation: "BRIN",
      },
      {
        id: "ID-KEMKOMINFO",
        abbreviation: "Kemkominfo",
      },
      {
        id: "ID-BSSN",
        abbreviation: "BSSN",
      },
    ],
  },
  {
    code: "PH",
    sourceCount: 12,
    authorityCount: 3,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["registration", "procurement", "liability"],
    authoritiesPreview: [
      {
        id: "PH-PHILSA",
        abbreviation: "PhilSA",
      },
      {
        id: "PH-NTC",
        abbreviation: "NTC",
      },
      {
        id: "PH-NPC",
        abbreviation: "NPC",
      },
    ],
  },
  {
    code: "SA",
    sourceCount: 12,
    authorityCount: 4,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: true,
    },
    topComplianceAreas: ["procurement", "liability", "registration"],
    authoritiesPreview: [
      {
        id: "SA-SSA",
        abbreviation: "SSA",
      },
      {
        id: "SA-CST",
        abbreviation: "CST",
      },
      {
        id: "SA-NCA",
        abbreviation: "NCA",
      },
    ],
  },
  {
    code: "EG",
    sourceCount: 11,
    authorityCount: 3,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["registration", "licensing", "frequency_spectrum"],
    authoritiesPreview: [
      {
        id: "EG-EGSA",
        abbreviation: "EgSA",
      },
      {
        id: "EG-NTRA",
        abbreviation: "NTRA",
      },
      {
        id: "EG-AFSA",
        abbreviation: "AfSA",
      },
    ],
  },
  {
    code: "AR",
    sourceCount: 10,
    authorityCount: 3,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["procurement", "registration", "licensing"],
    authoritiesPreview: [
      {
        id: "AR-CONAE",
        abbreviation: "CONAE",
      },
      {
        id: "AR-ENACOM",
        abbreviation: "ENACOM",
      },
      {
        id: "AR-INVAP",
        abbreviation: "INVAP",
      },
    ],
  },
  {
    code: "MX",
    sourceCount: 10,
    authorityCount: 3,
    treaties: {
      ost: true,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["registration", "licensing", "fdi_screening"],
    authoritiesPreview: [
      {
        id: "MX-AEM",
        abbreviation: "AEM",
      },
      {
        id: "MX-IFT",
        abbreviation: "IFT",
      },
      {
        id: "MX-INAI",
        abbreviation: "INAI",
      },
    ],
  },
  {
    code: "TW",
    sourceCount: 8,
    authorityCount: 5,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "military_dual_use", "registration"],
    authoritiesPreview: [
      {
        id: "TW-TASA",
        abbreviation: "",
      },
      {
        id: "TW-NSTC",
        abbreviation: "",
      },
      {
        id: "TW-NCC",
        abbreviation: "",
      },
    ],
  },
  {
    code: "KE",
    sourceCount: 7,
    authorityCount: 4,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "scientific_research", "registration"],
    authoritiesPreview: [
      {
        id: "KE-KSA",
        abbreviation: "",
      },
      {
        id: "KE-CAK",
        abbreviation: "",
      },
      {
        id: "KE-KCAA",
        abbreviation: "",
      },
    ],
  },
  {
    code: "CL",
    sourceCount: 7,
    authorityCount: 5,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: [
      "scientific_research",
      "licensing",
      "media_broadcasting",
    ],
    authoritiesPreview: [
      {
        id: "CL-SUBTEL",
        abbreviation: "",
      },
      {
        id: "CL-DGAC",
        abbreviation: "",
      },
      {
        id: "CL-MMA",
        abbreviation: "",
      },
    ],
  },
  {
    code: "NG",
    sourceCount: 7,
    authorityCount: 4,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["scientific_research", "licensing", "registration"],
    authoritiesPreview: [
      {
        id: "NG-NASRDA",
        abbreviation: "",
      },
      {
        id: "NG-NCC",
        abbreviation: "",
      },
      {
        id: "NG-NIGCOMSAT",
        abbreviation: "",
      },
    ],
  },
  {
    code: "VN",
    sourceCount: 7,
    authorityCount: 4,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["procurement", "frequency_spectrum", "licensing"],
    authoritiesPreview: [
      {
        id: "VN-VNSC",
        abbreviation: "",
      },
      {
        id: "VN-VAST",
        abbreviation: "",
      },
      {
        id: "VN-MIC",
        abbreviation: "",
      },
    ],
  },
  {
    code: "MA",
    sourceCount: 6,
    authorityCount: 4,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["scientific_research", "procurement", "licensing"],
    authoritiesPreview: [
      {
        id: "MA-CRTS",
        abbreviation: "",
      },
      {
        id: "MA-ANRT",
        abbreviation: "",
      },
      {
        id: "MA-FAR-SPACE",
        abbreviation: "",
      },
    ],
  },
  {
    code: "TH",
    sourceCount: 7,
    authorityCount: 4,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "registration", "scientific_research"],
    authoritiesPreview: [
      {
        id: "TH-GISTDA",
        abbreviation: "",
      },
      {
        id: "TH-NBTC",
        abbreviation: "",
      },
      {
        id: "TH-RTAF-SPACE",
        abbreviation: "",
      },
    ],
  },
  {
    code: "PK",
    sourceCount: 6,
    authorityCount: 3,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "registration", "scientific_research"],
    authoritiesPreview: [
      {
        id: "PK-SUPARCO",
        abbreviation: "",
      },
      {
        id: "PK-PTA",
        abbreviation: "",
      },
      {
        id: "PK-PSARA",
        abbreviation: "",
      },
    ],
  },
  {
    code: "DZ",
    sourceCount: 6,
    authorityCount: 3,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["scientific_research", "procurement", "licensing"],
    authoritiesPreview: [
      {
        id: "DZ-ASAL",
        abbreviation: "",
      },
      {
        id: "DZ-ARPT",
        abbreviation: "",
      },
      {
        id: "DZ-MDN-ESPACE",
        abbreviation: "",
      },
    ],
  },
  {
    code: "BD",
    sourceCount: 5,
    authorityCount: 3,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: [
      "registration",
      "frequency_spectrum",
      "media_broadcasting",
    ],
    authoritiesPreview: [
      {
        id: "BD-SPARRSO",
        abbreviation: "",
      },
      {
        id: "BD-BSCL",
        abbreviation: "",
      },
      {
        id: "BD-BTRC",
        abbreviation: "",
      },
    ],
  },
  {
    code: "IR",
    sourceCount: 6,
    authorityCount: 3,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: [
      "sanctions_compliance",
      "military_dual_use",
      "licensing",
    ],
    authoritiesPreview: [
      {
        id: "IR-ISA",
        abbreviation: "",
      },
      {
        id: "IR-IRGC-AEROSPACE",
        abbreviation: "",
      },
      {
        id: "IR-CRA",
        abbreviation: "",
      },
    ],
  },
  {
    code: "KZ",
    sourceCount: 6,
    authorityCount: 3,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["procurement", "licensing", "registration"],
    authoritiesPreview: [
      {
        id: "KZ-KAZCOSMOS",
        abbreviation: "",
      },
      {
        id: "KZ-MDDIAI",
        abbreviation: "",
      },
      {
        id: "KZ-KGS",
        abbreviation: "",
      },
    ],
  },
  {
    code: "KP",
    sourceCount: 5,
    authorityCount: 1,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: [
      "military_dual_use",
      "sanctions_compliance",
      "licensing",
    ],
    authoritiesPreview: [
      {
        id: "KP-NADA",
        abbreviation: "",
      },
    ],
  },
  {
    code: "MN",
    sourceCount: 4,
    authorityCount: 2,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["licensing", "procurement", "frequency_spectrum"],
    authoritiesPreview: [
      {
        id: "MN-MASLN",
        abbreviation: "",
      },
      {
        id: "MN-MOCDC",
        abbreviation: "",
      },
    ],
  },
  {
    code: "CO",
    sourceCount: 5,
    authorityCount: 3,
    treaties: {
      ost: false,
      liability: false,
      registration: false,
      moon: false,
      artemis: false,
    },
    topComplianceAreas: ["scientific_research", "licensing", "registration"],
    authoritiesPreview: [
      {
        id: "CO-CCE",
        abbreviation: "",
      },
      {
        id: "CO-CRC",
        abbreviation: "",
      },
      {
        id: "CO-FAC-SPACE",
        abbreviation: "",
      },
    ],
  },
];
