/**
 * Atlas draft-export helpers — turn any Astra-streamed answer into
 * a Word-compatible file the lawyer can open in Office Word, paste
 * into a memo, or store in their DMS.
 *
 * Why .doc and not .docx: shipping a .docx writer needs a 100kb+ deps
 * (`docx`, `docx-templates`, `pizzip`+`docxtemplater`). Word opens
 * `.doc` files containing Word-flavoured HTML (with the right MSO
 * meta tags) without complaint — has done since Word 2003. The file
 * keeps formatting (headings, bold, lists, tables), is a single
 * download, no new deps, and the partner double-clicks it open in
 * Word as expected.
 *
 * For the MD-native crowd (Notion, Obsidian) we also expose
 * `markdownExport` which is just a `.md` blob.
 *
 * Citation-pill markers in the source markdown — `[ATLAS-…]` and
 * `[CASE-…]` — are preserved as hyperlinks back to the Atlas
 * source/case detail page so a paste-into-email / paste-back-into-
 * Atlas-chat re-resolves them.
 */

import { exportPrefix, hasDisclaimer } from "./legal-disclaimers";

export type ExportLocale = "en" | "de";

const ATLAS_BASE_URL = "https://www.caelex.eu";

interface BrandingChrome {
  attribution: string;
  /** "Caelex · Confidential" repeating-header text */
  runningHeader: string;
  /** Footer separator line */
  pageLabel: (page: number, total: number) => string;
}

const CHROME_BY_LOCALE: Record<ExportLocale, BrandingChrome> = {
  en: {
    attribution: "Generated by Caelex Atlas",
    runningHeader: "Caelex · Confidential",
    pageLabel: (p, t) => `Page ${p} of ${t}`,
  },
  de: {
    attribution: "Erstellt mit Caelex Atlas",
    runningHeader: "Caelex · Vertraulich",
    pageLabel: (p, t) => `Seite ${p} von ${t}`,
  },
};

/**
 * Word-flavoured HTML preamble. The MSO conditional comment teaches
 * macOS Office 365 to open the file in Print Layout (Word's default
 * is Web Layout for HTML imports without it — looks broken on Mac).
 *
 * The `<w:HeaderFooter>` cluster registers a repeating page header
 * + page-number footer using Word's MSO XML islands. Without these
 * the printed memo has page numbers only on the last page.
 *
 * Citation-pill styling uses a 1pt border + small inset padding so
 * it survives Word's default print profile (which strips background
 * colors). Foreground emerald/violet text remains.
 */
function wordHead(locale: ExportLocale): string {
  const c = CHROME_BY_LOCALE[locale];
  const ATTR = escapeHtml(c.runningHeader);
  return `<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8" />
<meta name="ProgId" content="Word.Document" />
<meta name="Generator" content="Caelex Atlas" />
<!--[if gte mso 9]>
<xml>
  <w:WordDocument>
    <w:View>Print</w:View>
    <w:Zoom>100</w:Zoom>
    <w:DoNotOptimizeForBrowser/>
  </w:WordDocument>
</xml>
<![endif]-->
<style>
  @page WordSection1 { size: 21cm 29.7cm; margin: 2cm 2.5cm 2.5cm 2.5cm;
    mso-header-margin: 1cm; mso-footer-margin: 1cm;
    mso-header: url("#a1") h1; mso-footer: url("#a1") f1;
  }
  div.WordSection1 { page: WordSection1; }
  body { font-family: "Calibri", "Arial", sans-serif; font-size: 11pt; color: #111; line-height: 1.5; }
  h1 { font-size: 18pt; margin: 18pt 0 6pt 0; color: #111; }
  h2 { font-size: 14pt; margin: 14pt 0 4pt 0; color: #111; }
  h3 { font-size: 12pt; margin: 10pt 0 3pt 0; color: #333; }
  p { margin: 0 0 6pt 0; }
  blockquote { margin: 8pt 18pt; color: #444; border-left: 2pt solid #ccc; padding-left: 8pt; }
  table { border-collapse: collapse; margin: 8pt 0; }
  th, td { border: 1pt solid #ccc; padding: 4pt 6pt; vertical-align: top; }
  th { background: #f5f5f5; font-weight: 600; }
  td.right { text-align: right; }
  td.center { text-align: center; }
  code { font-family: "Consolas", monospace; background: #f4f4f4; padding: 0 2pt; border-radius: 2pt; }
  pre { font-family: "Consolas", monospace; background: #f4f4f4; padding: 6pt; border-radius: 2pt; white-space: pre-wrap; }
  .doc-footer { margin-top: 18pt; padding-top: 6pt; border-top: 1pt solid #e0e0e0; color: #888; font-size: 9pt; }
  /* Citation pills — border-only so the visual signal survives
     Word's default print profile (which drops background-color). */
  .citation { color: #047857; padding: 0 3pt; border: 1pt solid #047857; border-radius: 2pt; font-family: "Consolas", monospace; font-size: 10pt; text-decoration: none; }
  .citation-case { color: #6d28d9; border-color: #6d28d9; }
  .running-header { font-size: 9pt; color: #888; border-bottom: 0.5pt solid #ccc; padding-bottom: 4pt; }
  .running-footer { font-size: 9pt; color: #888; border-top: 0.5pt solid #ccc; padding-top: 4pt; text-align: right; }
</style>
</head>
<body>
<div style="mso-element:header" id="h1">
  <p class="running-header">${ATTR}</p>
</div>
<div style="mso-element:footer" id="f1">
  <p class="running-footer">${ATTR} — <span style="mso-field-code:PAGE"></span> / <span style="mso-field-code:NUMPAGES"></span></p>
</div>
<div class="WordSection1">`;
}

const WORD_FOOT = `</div></body></html>`;

/**
 * Minimal markdown → HTML converter. Covers the constructs Astra
 * actually emits: headings (#), bold (**), italic (*), inline code (`),
 * fenced code blocks (```), blockquotes (>), unordered + ordered
 * lists, horizontal rules (---), and pipe-tables with alignment
 * markers (`:--:`, `--:`).
 *
 * Citation tokens become hyperlinks back to atlas, so a paste-into-
 * email keeps the citations clickable. Styled with emerald/violet
 * borders so the visual signal survives Word's print profile.
 *
 * NOT a general-purpose Markdown parser — kept deliberately minimal
 * (~250 lines) because the Astra output schema is constrained.
 */
function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderInline(text: string): string {
  let out = escapeHtml(text);
  // Citation pills — hyperlinked back to Atlas. Run before bold/italic
  // so * inside pill text doesn't get parsed.
  out = out.replace(/\[CASE-[A-Z0-9-]+\]/g, (m) => {
    const id = m.slice(1, -1); // strip [ ]
    const href = `${ATLAS_BASE_URL}/atlas/cases/${encodeURIComponent(id)}`;
    return `<a class="citation citation-case" href="${href}">${m}</a>`;
  });
  out = out.replace(/\[ATLAS-[A-Z0-9-]+\]/g, (m) => {
    const id = m.slice(1, -1);
    const href = `${ATLAS_BASE_URL}/atlas/sources/${encodeURIComponent(id)}`;
    return `<a class="citation" href="${href}">${m}</a>`;
  });
  // Bold ** **
  out = out.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  // Italic * *  (but not inside a word like 1*2*3)
  out = out.replace(/(^|[^*])\*([^*\n]+)\*/g, "$1<em>$2</em>");
  // Inline code ` `
  out = out.replace(/`([^`]+)`/g, "<code>$1</code>");
  return out;
}

/**
 * Parse a markdown table separator row to extract per-column
 * alignment. `:---:` → "center", `---:` → "right", default "left".
 */
function parseTableAlignments(
  cells: string[],
): Array<"left" | "center" | "right"> {
  return cells.map((c) => {
    const trimmed = c.trim();
    const left = trimmed.startsWith(":");
    const right = trimmed.endsWith(":");
    if (left && right) return "center";
    if (right) return "right";
    return "left";
  });
}

function alignmentClass(a: "left" | "center" | "right"): string {
  if (a === "right") return ' class="right"';
  if (a === "center") return ' class="center"';
  return "";
}

function markdownToWordHtml(md: string): string {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  const out: string[] = [];
  let inUl = false;
  let inOl = false;
  let inCode = false;
  let codeBuf: string[] = [];
  let inTable = false;
  let tableSep = false;
  let tableAlignments: Array<"left" | "center" | "right"> = [];

  const flushList = () => {
    if (inUl) {
      out.push("</ul>");
      inUl = false;
    }
    if (inOl) {
      out.push("</ol>");
      inOl = false;
    }
  };
  const flushTable = () => {
    if (inTable) {
      out.push("</table>");
      inTable = false;
      tableSep = false;
      tableAlignments = [];
    }
  };

  for (const raw of lines) {
    const line = raw.trimEnd();

    if (inCode) {
      if (/^```/.test(line)) {
        out.push(`<pre>${escapeHtml(codeBuf.join("\n"))}</pre>`);
        codeBuf = [];
        inCode = false;
      } else {
        codeBuf.push(raw);
      }
      continue;
    }
    if (/^```/.test(line)) {
      flushList();
      flushTable();
      inCode = true;
      continue;
    }

    // Pipe table
    if (/^\s*\|.+\|\s*$/.test(line)) {
      const rawCells = line
        .trim()
        .replace(/^\||\|$/g, "")
        .split("|")
        .map((c) => c.trim());
      // Render cell content: empty → &nbsp; (raw entity, no escape so
      // Word doesn't render a zero-width column); non-empty → escaped
      // inline-rendered content.
      const renderCell = (c: string): string =>
        c.length === 0 ? "&nbsp;" : renderInline(c);

      if (!inTable) {
        flushList();
        out.push("<table>");
        inTable = true;
        out.push(
          `<thead><tr>${rawCells
            .map((c) => `<th>${renderCell(c)}</th>`)
            .join("")}</tr></thead><tbody>`,
        );
        continue;
      }
      // Separator row "| --- | :--: | ---: |" — parse alignment.
      if (
        !tableSep &&
        rawCells.every((c) => c.length === 0 || /^[-:]+$/.test(c))
      ) {
        tableSep = true;
        tableAlignments = parseTableAlignments(rawCells);
        continue;
      }
      out.push(
        `<tr>${rawCells
          .map((c, i) => {
            const align = tableAlignments[i] ?? "left";
            return `<td${alignmentClass(align)}>${renderCell(c)}</td>`;
          })
          .join("")}</tr>`,
      );
      continue;
    } else if (inTable) {
      out.push("</tbody>");
      flushTable();
    }

    // Horizontal rule
    if (/^---+$/.test(line)) {
      flushList();
      out.push("<hr/>");
      continue;
    }

    // Headings
    const h = /^(#{1,3})\s+(.+)$/.exec(line);
    if (h) {
      flushList();
      const level = Math.min(h[1].length, 3);
      out.push(`<h${level}>${renderInline(h[2])}</h${level}>`);
      continue;
    }

    // Blockquote
    if (/^>\s+/.test(line)) {
      flushList();
      out.push(
        `<blockquote>${renderInline(line.replace(/^>\s+/, ""))}</blockquote>`,
      );
      continue;
    }

    // Unordered list
    if (/^\s*[-*]\s+/.test(line)) {
      if (!inUl) {
        flushList();
        out.push("<ul>");
        inUl = true;
      }
      out.push(`<li>${renderInline(line.replace(/^\s*[-*]\s+/, ""))}</li>`);
      continue;
    }

    // Ordered list
    if (/^\s*\d+\.\s+/.test(line)) {
      if (!inOl) {
        flushList();
        out.push("<ol>");
        inOl = true;
      }
      out.push(`<li>${renderInline(line.replace(/^\s*\d+\.\s+/, ""))}</li>`);
      continue;
    }

    // Empty line
    if (line.trim() === "") {
      flushList();
      continue;
    }

    // Default — paragraph
    flushList();
    out.push(`<p>${renderInline(line)}</p>`);
  }
  flushList();
  flushTable();
  if (inCode && codeBuf.length > 0) {
    out.push(`<pre>${escapeHtml(codeBuf.join("\n"))}</pre>`);
  }
  return out.join("\n");
}

/**
 * Build a filesystem-safe filename from an arbitrary title.
 *
 * Strips characters that are forbidden by Windows / macOS / Linux
 * (`<>:"/\\|?*` plus control chars), collapses whitespace to dashes,
 * lowercases, and caps at 60 chars. Preserves digits, hyphens, dots,
 * and Unicode letters — so a German title like "DE-Lizenz vom
 * 27.04.2026" survives as "de-lizenz-vom-27.04.2026" instead of
 * collapsing to nothing.
 *
 * Earlier version used `/[ -<>:"/\\|?*]+/g` which is a *character
 * range* from space (0x20) to `<` (0x3C) — it accidentally stripped
 * digits, hyphens, parentheses, and most punctuation. That made
 * every export download with the same fallback name.
 */
function safeFilename(s: string): string {
  // 1. Strip the actual forbidden set (no character ranges; backslash
  //    + pipe + question mark + asterisk + colon + double-quote +
  //    angle brackets + control chars 0x00-0x1F).
  // eslint-disable-next-line no-control-regex
  const forbidden = /[<>:"/\\|?*\x00-\x1f]+/g;
  const cleaned = s.replace(forbidden, "");
  // 2. Collapse whitespace to single dashes.
  const dashed = cleaned.replace(/\s+/g, "-");
  // 3. Trim leading/trailing dashes and dots (Windows: trailing dot
  //    is stripped by the OS; we strip both ends ourselves).
  const trimmed = dashed.replace(/^[-.]+|[-.]+$/g, "");
  // 4. Cap at 60 chars and lowercase. Empty → fallback.
  const final = trimmed.slice(0, 60).toLowerCase();
  return final || "atlas-draft";
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

/**
 * Locale-aware date stamp for the export footer.
 *   en → "27 Apr 2026, 14:32"
 *   de → "27.04.2026, 14:32"
 */
function formatStamp(date: Date, locale: ExportLocale): string {
  const opts: Intl.DateTimeFormatOptions = {
    day: "2-digit",
    month: locale === "de" ? "2-digit" : "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  };
  return new Intl.DateTimeFormat(
    locale === "de" ? "de-DE" : "en-GB",
    opts,
  ).format(date);
}

/**
 * Append a YYYY-MM-DD date to the filename so consecutive exports
 * don't overwrite each other in the user's downloads folder. Without
 * this, every "Compliance brief.doc" replaced the previous one.
 */
function withDatedSuffix(base: string): string {
  const d = new Date();
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  return `${base}-${yyyy}${mm}${dd}`;
}

/**
 * Strip a leading H1 from markdown so the synthesized H1 (built from
 * the title arg or the first non-empty line) doesn't duplicate the
 * body's own heading. Preserves the rest of the body verbatim.
 */
function stripLeadingH1(md: string): string {
  const lines = md.replace(/\r\n/g, "\n").split("\n");
  let i = 0;
  // Skip leading blank lines.
  while (i < lines.length && lines[i].trim() === "") i++;
  // If the first non-blank line is an H1, drop it.
  if (i < lines.length && /^#\s+/.test(lines[i])) {
    lines.splice(i, 1);
    // Also drop a trailing blank after the dropped H1 so the body
    // doesn't get an extra blank paragraph at the top.
    if (i < lines.length && lines[i].trim() === "") {
      lines.splice(i, 1);
    }
  }
  return lines.join("\n");
}

/**
 * Download the markdown content as a Word-compatible `.doc` file.
 * Word opens it directly with formatting preserved.
 *
 * `title` is rendered as the document's H1; if absent we derive one
 * from the first line of the markdown. If the markdown body itself
 * begins with an H1 we strip it so the document doesn't get two
 * stacked titles.
 */
export function exportDraftAsWord(opts: {
  markdown: string;
  title?: string;
  /** Locale for chrome (footer attribution, header, date format).
   *  Defaults to "en". The pilot is German — wire your useLanguage()
   *  result through here to get a fully German export. */
  locale?: ExportLocale;
  /** Footer attribution override. Defaults to the locale-appropriate
   *  "Generated by Caelex Atlas" / "Erstellt mit Caelex Atlas". */
  attribution?: string;
}) {
  const locale: ExportLocale = opts.locale ?? "en";
  const chrome = CHROME_BY_LOCALE[locale];
  const attribution = opts.attribution ?? chrome.attribution;
  const inferredTitle =
    opts.title ||
    opts.markdown
      .split("\n")
      .map((l) => l.replace(/^#+\s*/, "").trim())
      .find((l) => l.length > 0) ||
    "Atlas draft";
  // Drop a leading H1 so we don't render the title twice.
  const cleanedBody = stripLeadingH1(opts.markdown);
  // ─── Compliance back-stop: legal-review disclaimer ───
  // The Astra route already injects the disclaimer at the end of
  // every drafting-tool turn (see app/api/atlas/ai-chat/route.ts).
  // But: the user could have pasted the answer into Notion, edited
  // it, deleted the disclaimer block, and then re-imported via the
  // markdown export path. To make the disclaimer truly mandatory in
  // every artifact a partner shares with their client, we ALWAYS
  // ensure it leads the document — adding it back if the source
  // text dropped it.
  const bodyWithDisclaimer = hasDisclaimer(cleanedBody)
    ? cleanedBody
    : exportPrefix(locale) + cleanedBody;
  const body = markdownToWordHtml(bodyWithDisclaimer);
  const stamp = formatStamp(new Date(), locale);
  const html = `${wordHead(locale)}
<h1>${escapeHtml(inferredTitle)}</h1>
${body}
<p class="doc-footer">${escapeHtml(attribution)} · ${escapeHtml(stamp)}</p>
${WORD_FOOT}`;
  const blob = new Blob([html], { type: "application/msword" });
  const filename = `${withDatedSuffix(safeFilename(inferredTitle))}.doc`;
  downloadBlob(blob, filename);
}

/**
 * Download as plain markdown — for partners using Notion / Obsidian /
 * a non-Word DMS.
 */
export function exportDraftAsMarkdown(opts: {
  markdown: string;
  title?: string;
  /** Locale for the legal-review disclaimer prepended when missing.
   *  Defaults to "en". Match the user's session language for the DE
   *  pilot. */
  locale?: ExportLocale;
}) {
  const locale: ExportLocale = opts.locale ?? "en";
  const inferredTitle =
    opts.title ||
    opts.markdown
      .split("\n")
      .map((l) => l.replace(/^#+\s*/, "").trim())
      .find((l) => l.length > 0) ||
    "atlas-draft";
  // Same back-stop as the .doc path — guarantee the legal-review
  // disclaimer leads every exported markdown file regardless of
  // whether the source text already carried one.
  const finalMarkdown = hasDisclaimer(opts.markdown)
    ? opts.markdown
    : exportPrefix(locale) + opts.markdown;
  const blob = new Blob([finalMarkdown], {
    type: "text/markdown;charset=utf-8",
  });
  const filename = `${withDatedSuffix(safeFilename(inferredTitle))}.md`;
  downloadBlob(blob, filename);
}
