export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED",
  AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  TENANT_MISMATCH = "TENANT_MISMATCH",
  KEY_EXPIRED = "KEY_EXPIRED",
  KEY_REVOKED = "KEY_REVOKED",
  KEY_ALREADY_ROTATED = "KEY_ALREADY_ROTATED",
  KEY_ALREADY_REVOKED = "KEY_ALREADY_REVOKED",
  ATTESTATION_REVOKED = "ATTESTATION_REVOKED",
  ATTESTATION_NOT_FOUND = "ATTESTATION_NOT_FOUND",
  CERTIFICATE_NOT_FOUND = "CERTIFICATE_NOT_FOUND",
  NONCE_COLLISION = "NONCE_COLLISION",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}

const STATUS_CODE_MAP: Record<ErrorCode, number> = {
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.AUTHENTICATION_REQUIRED]: 401,
  [ErrorCode.AUTHENTICATION_FAILED]: 401,
  [ErrorCode.PERMISSION_DENIED]: 403,
  [ErrorCode.RESOURCE_NOT_FOUND]: 404,
  [ErrorCode.TENANT_MISMATCH]: 403,
  [ErrorCode.KEY_EXPIRED]: 422,
  [ErrorCode.KEY_REVOKED]: 422,
  [ErrorCode.KEY_ALREADY_ROTATED]: 409,
  [ErrorCode.KEY_ALREADY_REVOKED]: 409,
  [ErrorCode.ATTESTATION_REVOKED]: 422,
  [ErrorCode.ATTESTATION_NOT_FOUND]: 404,
  [ErrorCode.CERTIFICATE_NOT_FOUND]: 404,
  [ErrorCode.NONCE_COLLISION]: 409,
  [ErrorCode.RATE_LIMIT_EXCEEDED]: 429,
  [ErrorCode.INTERNAL_ERROR]: 500,
};

export class ApiError extends Error {
  public readonly code: ErrorCode;
  public readonly statusCode: number;

  constructor(code: ErrorCode, message: string) {
    super(message);
    this.name = "ApiError";
    this.code = code;
    this.statusCode = STATUS_CODE_MAP[code];
    Object.setPrototypeOf(this, ApiError.prototype);
  }
}
