import { describe, it, expect, vi, beforeEach } from "vitest";
import React from "react";
import { render, screen } from "@testing-library/react";

// ─── Hoisted mock variables ───
const mockToBlob = vi.hoisted(() => vi.fn());
const mockPdf = vi.hoisted(() => vi.fn());

vi.mock("@react-pdf/renderer", () => ({
  Document: ({ children }: any) => <div data-testid="document">{children}</div>,
  Page: ({ children, ...props }: any) => (
    <div data-testid="page" {...props}>
      {children}
    </div>
  ),
  Text: ({ children, ...props }: any) => <span {...props}>{children}</span>,
  View: ({ children, ...props }: any) => <div {...props}>{children}</div>,
  StyleSheet: { create: (styles: any) => styles },
  Font: { register: vi.fn() },
  pdf: mockPdf,
}));

import { generateDocumentPDFBlob } from "./client-generator";
import type { ReportSection } from "./types";

beforeEach(() => {
  vi.clearAllMocks();
  mockToBlob.mockResolvedValue(new Blob(["pdf"], { type: "application/pdf" }));
  mockPdf.mockReturnValue({ toBlob: mockToBlob });
});

// ─── generateDocumentPDFBlob ───

describe("generateDocumentPDFBlob", () => {
  it("calls pdf() and toBlob() and returns a Blob", async () => {
    const sections: ReportSection[] = [
      {
        title: "Section 1",
        content: [{ type: "text", value: "Hello World" }],
      },
    ];

    const blob = await generateDocumentPDFBlob("Test Report", sections);

    expect(mockPdf).toHaveBeenCalledOnce();
    expect(mockToBlob).toHaveBeenCalledOnce();
    expect(blob).toBeInstanceOf(Blob);
  });

  it("passes correct JSX element to pdf()", async () => {
    const sections: ReportSection[] = [
      {
        title: "Summary",
        content: [{ type: "text", value: "Summary text" }],
      },
    ];

    await generateDocumentPDFBlob("My Title", sections);

    // pdf() should receive a React element
    const arg = mockPdf.mock.calls[0][0];
    expect(React.isValidElement(arg)).toBe(true);
  });

  it("handles empty sections array", async () => {
    const blob = await generateDocumentPDFBlob("Empty Report", []);

    expect(mockPdf).toHaveBeenCalledOnce();
    expect(blob).toBeInstanceOf(Blob);
  });
});

// ─── GeneratedDocumentPDF rendering (tested indirectly via generateDocumentPDFBlob) ───
// We extract the element passed to pdf() and render it via @testing-library/react

describe("GeneratedDocumentPDF (internal component)", () => {
  async function renderPdfComponent(title: string, sections: ReportSection[]) {
    await generateDocumentPDFBlob(title, sections);
    const element = mockPdf.mock.calls[0][0];
    return render(element);
  }

  it("renders the title in the header", async () => {
    const { container } = await renderPdfComponent("Authorization Report", []);
    expect(container.textContent).toContain("Authorization Report");
  });

  it("renders the disclaimer text", async () => {
    const { container } = await renderPdfComponent("Test Report", []);
    expect(container.textContent).toContain("For informational purposes only");
  });

  it("renders section titles", async () => {
    const sections: ReportSection[] = [
      {
        title: "Overview",
        content: [{ type: "text", value: "Overview content" }],
      },
      {
        title: "Details",
        content: [{ type: "text", value: "Detail content" }],
      },
    ];
    const { container } = await renderPdfComponent("Report", sections);
    expect(container.textContent).toContain("Overview");
    expect(container.textContent).toContain("Details");
  });

  it("renders footer text", async () => {
    const { container } = await renderPdfComponent("Report", []);
    expect(container.textContent).toContain("Generated by Caelex");
    expect(container.textContent).toContain("CONFIDENTIAL");
  });
});

// ─── renderBlock coverage ───

describe("renderBlock (internal function) — block types", () => {
  async function renderWithBlock(block: Record<string, unknown>) {
    const sections: ReportSection[] = [
      {
        title: "Test Section",
        content: [block as any],
      },
    ];
    await generateDocumentPDFBlob("Test", sections);
    const element = mockPdf.mock.calls[0][0];
    return render(element);
  }

  it("renders text block", async () => {
    const { container } = await renderWithBlock({
      type: "text",
      value: "Hello text",
    });
    expect(container.textContent).toContain("Hello text");
  });

  it("renders heading block with level 2 (default)", async () => {
    const { container } = await renderWithBlock({
      type: "heading",
      value: "Section Heading",
      level: 2,
    });
    expect(container.textContent).toContain("Section Heading");
  });

  it("renders heading block with level 3", async () => {
    const { container } = await renderWithBlock({
      type: "heading",
      value: "Sub Heading",
      level: 3,
    });
    expect(container.textContent).toContain("Sub Heading");
  });

  it("renders unordered list block", async () => {
    const { container } = await renderWithBlock({
      type: "list",
      items: ["Item A", "Item B"],
      ordered: false,
    });
    expect(container.textContent).toContain("Item A");
    expect(container.textContent).toContain("Item B");
  });

  it("renders ordered list block", async () => {
    const { container } = await renderWithBlock({
      type: "list",
      items: ["First", "Second"],
      ordered: true,
    });
    expect(container.textContent).toContain("1.");
    expect(container.textContent).toContain("2.");
    expect(container.textContent).toContain("First");
    expect(container.textContent).toContain("Second");
  });

  it("renders list block with empty items array", async () => {
    const { container } = await renderWithBlock({
      type: "list",
      items: [],
    });
    // Should render without error
    expect(container).toBeTruthy();
  });

  it("renders table block", async () => {
    const { container } = await renderWithBlock({
      type: "table",
      headers: ["Name", "Value"],
      rows: [
        ["Alpha", "100"],
        ["Beta", "200"],
      ],
    });
    expect(container.textContent).toContain("Name");
    expect(container.textContent).toContain("Value");
    expect(container.textContent).toContain("Alpha");
    expect(container.textContent).toContain("200");
  });

  it("renders table with non-array rows filtered out", async () => {
    const { container } = await renderWithBlock({
      type: "table",
      headers: ["H"],
      rows: ["not-an-array", ["valid", "row"]] as any,
    });
    expect(container.textContent).toContain("valid");
  });

  it("renders keyValue block", async () => {
    const { container } = await renderWithBlock({
      type: "keyValue",
      items: [
        { key: "Color", value: "Blue" },
        { key: "Size", value: "Large" },
      ],
    });
    expect(container.textContent).toContain("Color");
    expect(container.textContent).toContain("Blue");
    expect(container.textContent).toContain("Size");
    expect(container.textContent).toContain("Large");
  });

  it("filters out non-object items in keyValue block", async () => {
    const { container } = await renderWithBlock({
      type: "keyValue",
      items: [null, "invalid", { key: "Valid", value: "Item" }] as any,
    });
    expect(container.textContent).toContain("Valid");
    expect(container.textContent).toContain("Item");
  });

  it("renders alert block with info severity", async () => {
    const { container } = await renderWithBlock({
      type: "alert",
      severity: "info",
      message: "Info message here",
    });
    expect(container.textContent).toContain("Info message here");
  });

  it("renders alert block with warning severity", async () => {
    const { container } = await renderWithBlock({
      type: "alert",
      severity: "warning",
      message: "Warning message",
    });
    expect(container.textContent).toContain("Warning message");
  });

  it("renders alert block with error severity", async () => {
    const { container } = await renderWithBlock({
      type: "alert",
      severity: "error",
      message: "Error occurred",
    });
    expect(container.textContent).toContain("Error occurred");
  });

  it("renders divider block", async () => {
    const { container } = await renderWithBlock({
      type: "divider",
    });
    // Should render without error (divider is just a styled View)
    expect(container).toBeTruthy();
  });

  it("renders spacer block with custom height", async () => {
    const { container } = await renderWithBlock({
      type: "spacer",
      height: 40,
    });
    expect(container).toBeTruthy();
  });

  it("renders spacer block with default height when not specified", async () => {
    const { container } = await renderWithBlock({
      type: "spacer",
    });
    expect(container).toBeTruthy();
  });

  it("returns null for unknown block type", async () => {
    const { container } = await renderWithBlock({
      type: "unknown_type",
      value: "ignored",
    });
    // The unknown block produces null, but the section still renders
    expect(container.textContent).toContain("Test Section");
  });

  it("returns null for block without type", async () => {
    const { container } = await renderWithBlock({
      value: "no type set",
    });
    expect(container.textContent).toContain("Test Section");
  });

  it("returns null for null/undefined block", async () => {
    const sections: ReportSection[] = [
      {
        title: "Test Section",
        content: [null as any, undefined as any],
      },
    ];
    await generateDocumentPDFBlob("Test", sections);
    const element = mockPdf.mock.calls[0][0];
    const { container } = render(element);
    expect(container.textContent).toContain("Test Section");
  });
});

// ─── str() helper coverage (tested indirectly through renderBlock) ───

describe("str helper (internal function)", () => {
  async function renderTextBlock(value: unknown) {
    const sections: ReportSection[] = [
      {
        title: "S",
        content: [{ type: "text", value } as any],
      },
    ];
    await generateDocumentPDFBlob("T", sections);
    const element = mockPdf.mock.calls[0][0];
    return render(element);
  }

  it("handles string value", async () => {
    const { container } = await renderTextBlock("hello");
    expect(container.textContent).toContain("hello");
  });

  it("handles number value", async () => {
    const { container } = await renderTextBlock(42);
    expect(container.textContent).toContain("42");
  });

  it("handles boolean value", async () => {
    const { container } = await renderTextBlock(true);
    expect(container.textContent).toContain("true");
  });

  it("handles null value", async () => {
    const { container } = await renderTextBlock(null);
    // str(null) returns ""
    expect(container).toBeTruthy();
  });

  it("handles undefined value", async () => {
    const { container } = await renderTextBlock(undefined);
    expect(container).toBeTruthy();
  });

  it("handles object value (JSON.stringify)", async () => {
    const { container } = await renderTextBlock({ foo: "bar" });
    expect(container.textContent).toContain("foo");
    expect(container.textContent).toContain("bar");
  });
});
