/**
 * PDF Generator using jsPDF
 *
 * Pure JavaScript — zero React dependency.
 * Generates professional compliance documents from ReportSection[] data.
 */

import { jsPDF } from "jspdf";
import "jspdf-autotable";
import type { ReportSection } from "./types";

// ─── Layout Constants (mm) ───

const PAGE_W = 210;
const MARGIN_L = 20;
const MARGIN_R = 20;
const MARGIN_T = 25;
const MARGIN_B = 35;
const CONTENT_W = PAGE_W - MARGIN_L - MARGIN_R;
const PAGE_H = 297;
const MAX_Y = PAGE_H - MARGIN_B;

// ─── Colors ───

const COL = {
  primary: [30, 58, 95] as [number, number, number], // #1E3A5F
  body: [45, 55, 72] as [number, number, number], // #2D3748
  secondary: [74, 85, 104] as [number, number, number], // #4A5568
  muted: [113, 128, 150] as [number, number, number], // #718096
  light: [160, 174, 192] as [number, number, number], // #A0AEC0
  border: [226, 232, 240] as [number, number, number], // #E2E8F0
  red: [229, 62, 62] as [number, number, number], // #E53E3E
  alertInfoBg: [235, 248, 255] as [number, number, number],
  alertInfoText: [43, 108, 176] as [number, number, number],
  alertWarnBg: [255, 250, 240] as [number, number, number],
  alertWarnText: [192, 86, 33] as [number, number, number],
  alertErrBg: [255, 245, 245] as [number, number, number],
  alertErrText: [197, 48, 48] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  headerBg: [247, 250, 252] as [number, number, number],
};

// ─── Helpers ───

function str(v: unknown): string {
  if (v == null) return "";
  if (typeof v === "string") return v;
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  try {
    return JSON.stringify(v);
  } catch {
    return "";
  }
}

// ─── PDF Builder ───

class DocumentPDFBuilder {
  private doc: jsPDF;
  private y: number = MARGIN_T;
  private pageNum: number = 1;
  private title: string;

  constructor(title: string) {
    this.title = title;
    this.doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    this.doc.setFont("helvetica", "normal");
  }

  private checkPageBreak(neededHeight: number) {
    if (this.y + neededHeight > MAX_Y) {
      this.addFooter();
      this.doc.addPage();
      this.pageNum++;
      this.y = MARGIN_T;
    }
  }

  private addFooter() {
    const footerY = PAGE_H - 20;
    // Divider line
    this.doc.setDrawColor(...COL.border);
    this.doc.setLineWidth(0.3);
    this.doc.line(MARGIN_L, footerY, PAGE_W - MARGIN_R, footerY);

    // Left text
    this.doc.setFontSize(7);
    this.doc.setTextColor(...COL.light);
    this.doc.setFont("helvetica", "normal");
    this.doc.text(
      "Generated by Caelex (caelex.eu). Not legal advice.",
      MARGIN_L,
      footerY + 4,
    );

    // Center - CONFIDENTIAL
    this.doc.setFontSize(6);
    this.doc.setTextColor(...COL.red);
    this.doc.setFont("helvetica", "bold");
    this.doc.text("CONFIDENTIAL", PAGE_W / 2, footerY + 4, {
      align: "center",
    });

    // Right - page number
    this.doc.setFontSize(8);
    this.doc.setTextColor(...COL.secondary);
    this.doc.setFont("helvetica", "normal");
    this.doc.text(`Page ${this.pageNum}`, PAGE_W - MARGIN_R, footerY + 4, {
      align: "right",
    });
  }

  renderHeader(subtitle: string) {
    // Title
    this.doc.setFontSize(18);
    this.doc.setTextColor(...COL.primary);
    this.doc.setFont("helvetica", "bold");
    const titleLines = this.doc.splitTextToSize(this.title, CONTENT_W);
    this.doc.text(titleLines, MARGIN_L, this.y);
    this.y += titleLines.length * 7 + 2;

    // Subtitle
    this.doc.setFontSize(11);
    this.doc.setTextColor(...COL.secondary);
    this.doc.setFont("helvetica", "normal");
    this.doc.text(subtitle, MARGIN_L, this.y);
    this.y += 6;

    // Report date
    this.doc.setFontSize(9);
    this.doc.setTextColor(...COL.muted);
    const dateStr = `Report Date: ${new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" })}`;
    this.doc.text(dateStr, MARGIN_L, this.y);
    this.y += 4;

    // Header line
    this.doc.setDrawColor(...COL.primary);
    this.doc.setLineWidth(0.8);
    this.doc.line(MARGIN_L, this.y, PAGE_W - MARGIN_R, this.y);
    this.y += 8;

    // Disclaimer
    this.doc.setFontSize(7);
    this.doc.setTextColor(...COL.red);
    this.doc.setFont("helvetica", "bold");
    this.doc.text(
      "FOR INFORMATIONAL PURPOSES ONLY — NOT LEGAL ADVICE",
      PAGE_W / 2,
      this.y,
      { align: "center" },
    );
    this.doc.setFont("helvetica", "normal");
    this.y += 10;
  }

  renderSection(section: { title: string; content: unknown[] }) {
    const titleText = str(section.title);

    // Section title
    this.checkPageBreak(15);
    this.doc.setFontSize(13);
    this.doc.setTextColor(...COL.primary);
    this.doc.setFont("helvetica", "bold");
    this.doc.text(titleText, MARGIN_L, this.y);
    this.y += 5;

    // Section underline
    this.doc.setDrawColor(...COL.border);
    this.doc.setLineWidth(0.3);
    this.doc.line(MARGIN_L, this.y, PAGE_W - MARGIN_R, this.y);
    this.y += 6;

    // Content blocks
    const content = Array.isArray(section.content) ? section.content : [];
    for (const block of content) {
      if (!block || typeof block !== "object") continue;
      this.renderBlock(block as Record<string, unknown>);
    }

    this.y += 4;
  }

  private renderBlock(block: Record<string, unknown>) {
    const type = String(block.type || "");

    switch (type) {
      case "text":
        this.renderText(str(block.value));
        break;
      case "heading":
        this.renderHeading(str(block.value), block.level === 3 ? 3 : 2);
        break;
      case "list":
        this.renderList(
          Array.isArray(block.items) ? block.items : [],
          block.ordered === true,
        );
        break;
      case "table":
        this.renderTable(
          Array.isArray(block.headers) ? block.headers : [],
          Array.isArray(block.rows) ? block.rows : [],
        );
        break;
      case "keyValue":
        this.renderKeyValue(Array.isArray(block.items) ? block.items : []);
        break;
      case "alert":
        this.renderAlert(str(block.message), String(block.severity || "info"));
        break;
      case "divider":
        this.renderDivider();
        break;
      case "spacer":
        this.y += typeof block.height === "number" ? block.height * 0.35 : 5;
        break;
    }
  }

  private renderText(text: string) {
    if (!text) return;
    this.doc.setFontSize(10);
    this.doc.setTextColor(...COL.body);
    this.doc.setFont("helvetica", "normal");
    const lines = this.doc.splitTextToSize(text, CONTENT_W);
    const lineHeight = 4.5;
    const totalHeight = lines.length * lineHeight;
    this.checkPageBreak(totalHeight);
    this.doc.text(lines, MARGIN_L, this.y);
    this.y += totalHeight + 3;
  }

  private renderHeading(text: string, level: number) {
    if (!text) return;
    this.checkPageBreak(12);
    this.y += 3;
    if (level === 2) {
      this.doc.setFontSize(12);
      this.doc.setTextColor(...COL.body);
    } else {
      this.doc.setFontSize(11);
      this.doc.setTextColor(...COL.secondary);
    }
    this.doc.setFont("helvetica", "bold");
    const lines = this.doc.splitTextToSize(text, CONTENT_W);
    this.doc.text(lines, MARGIN_L, this.y);
    this.y += lines.length * 5 + 3;
  }

  private renderList(items: unknown[], ordered: boolean) {
    if (items.length === 0) return;
    this.doc.setFontSize(10);
    this.doc.setTextColor(...COL.body);
    this.doc.setFont("helvetica", "normal");

    const indent = 8;
    const bulletWidth = ordered ? 8 : 5;
    const textWidth = CONTENT_W - indent - bulletWidth;

    for (let i = 0; i < items.length; i++) {
      const text = str(items[i]);
      const lines = this.doc.splitTextToSize(text, textWidth);
      const height = lines.length * 4.5;
      this.checkPageBreak(height);

      // Bullet/number
      this.doc.setTextColor(...COL.secondary);
      const bullet = ordered ? `${i + 1}.` : "\u2022";
      this.doc.text(bullet, MARGIN_L + indent, this.y);

      // Text
      this.doc.setTextColor(...COL.body);
      this.doc.text(lines, MARGIN_L + indent + bulletWidth, this.y);
      this.y += height + 1.5;
    }
    this.y += 2;
  }

  private renderTable(headers: unknown[], rows: unknown[]) {
    if (headers.length === 0 && rows.length === 0) return;

    const head = [headers.map((h) => str(h))];
    const body = rows
      .filter((r) => Array.isArray(r))
      .map((row) => (row as unknown[]).map((cell) => str(cell)));

    if (body.length === 0 && head[0].length === 0) return;

    this.checkPageBreak(20);

    // Use jspdf-autotable
    (this.doc as unknown as { autoTable: (opts: unknown) => void }).autoTable({
      startY: this.y,
      head: head[0].length > 0 ? head : undefined,
      body,
      margin: { left: MARGIN_L, right: MARGIN_R },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        textColor: COL.body,
        lineColor: COL.border,
        lineWidth: 0.2,
      },
      headStyles: {
        fillColor: COL.headerBg,
        textColor: COL.primary,
        fontStyle: "bold",
        lineWidth: 0.2,
      },
      alternateRowStyles: {
        fillColor: [252, 252, 253],
      },
      didDrawPage: () => {
        // Update Y after table renders
      },
    });

    // Get final Y position after autotable
    const finalY = (
      this.doc as unknown as { lastAutoTable: { finalY: number } }
    ).lastAutoTable?.finalY;
    if (finalY) {
      this.y = finalY + 5;
    } else {
      this.y += 15;
    }
  }

  private renderKeyValue(items: unknown[]) {
    if (items.length === 0) return;

    this.doc.setFontSize(9);
    const keyWidth = CONTENT_W * 0.35;
    const valWidth = CONTENT_W * 0.65;

    for (const item of items) {
      if (!item || typeof item !== "object") continue;
      const rec = item as Record<string, unknown>;
      const key = str(rec.key);
      const value = str(rec.value);

      const valLines = this.doc.splitTextToSize(value, valWidth - 5);
      const height = Math.max(valLines.length * 4, 5);
      this.checkPageBreak(height + 2);

      // Key
      this.doc.setFont("helvetica", "bold");
      this.doc.setTextColor(...COL.secondary);
      this.doc.text(key, MARGIN_L, this.y);

      // Value
      this.doc.setFont("helvetica", "normal");
      this.doc.setTextColor(...COL.body);
      this.doc.text(valLines, MARGIN_L + keyWidth, this.y);

      this.y += height;

      // Separator line
      this.doc.setDrawColor(...COL.border);
      this.doc.setLineWidth(0.1);
      this.doc.line(MARGIN_L, this.y, PAGE_W - MARGIN_R, this.y);
      this.y += 3;
    }
    this.y += 2;
  }

  private renderAlert(message: string, severity: string) {
    if (!message) return;

    const bgColor =
      severity === "warning"
        ? COL.alertWarnBg
        : severity === "error"
          ? COL.alertErrBg
          : COL.alertInfoBg;
    const textColor =
      severity === "warning"
        ? COL.alertWarnText
        : severity === "error"
          ? COL.alertErrText
          : COL.alertInfoText;
    const borderColor =
      severity === "warning"
        ? COL.alertWarnText
        : severity === "error"
          ? COL.alertErrText
          : COL.alertInfoText;

    this.doc.setFontSize(9);
    const lines = this.doc.splitTextToSize(message, CONTENT_W - 12);
    const boxHeight = lines.length * 4 + 8;
    this.checkPageBreak(boxHeight);

    // Background
    this.doc.setFillColor(...bgColor);
    this.doc.roundedRect(MARGIN_L, this.y - 2, CONTENT_W, boxHeight, 1, 1, "F");

    // Left border
    this.doc.setFillColor(...borderColor);
    this.doc.rect(MARGIN_L, this.y - 2, 1.5, boxHeight, "F");

    // Text
    this.doc.setTextColor(...textColor);
    this.doc.setFont("helvetica", "normal");
    this.doc.text(lines, MARGIN_L + 6, this.y + 3);

    this.y += boxHeight + 4;
  }

  private renderDivider() {
    this.checkPageBreak(8);
    this.y += 4;
    this.doc.setDrawColor(...COL.border);
    this.doc.setLineWidth(0.3);
    this.doc.line(MARGIN_L, this.y, PAGE_W - MARGIN_R, this.y);
    this.y += 6;
  }

  finalize(): Blob {
    // Add footer to last page
    this.addFooter();
    return this.doc.output("blob");
  }
}

// ─── Public API ───

export function generateDocumentPDF(
  title: string,
  sections: ReportSection[],
): Blob {
  const builder = new DocumentPDFBuilder(title);

  // Header
  const subtitle = `Generated by ASTRA AI — ${new Date().toLocaleDateString("en-GB")}`;
  builder.renderHeader(subtitle);

  // Sections
  for (const section of sections) {
    builder.renderSection({
      title: str(section.title),
      content: Array.isArray(section.content) ? section.content : [],
    });
  }

  return builder.finalize();
}
