"use client";

import * as React from "react";
import { Bot, X } from "lucide-react";

/**
 * AI-Disclosure Banner — Sprint 6C (EU AI Act Art. 50 §1)
 *
 * Art. 50 requires that "natural persons... are informed that they
 * are interacting with an AI system". For chat surfaces this is
 * satisfied by a clear, prominent disclosure on the first interaction.
 *
 * # Behaviour
 *
 *   - Renders at the top of any Astra chat surface
 *   - Dismissible — once dismissed, hidden for 24h via localStorage
 *   - Non-blocking — the chat continues to render below it
 *   - The disclosure label always visible somewhere (the message
 *     footer in `AIMessageFooter` covers per-message disclosure
 *     even after the banner is dismissed)
 *
 * # Why dismissible-with-TTL not permanent
 *
 *   - Permanent dismiss = compliance risk (regulators want
 *     freshness, not "user clicked X once 18 months ago")
 *   - 24h TTL is the conservative interpretation of "session-based"
 *     for a SaaS that operators may leave open across days
 *   - The footer disclosure on every message satisfies Art. 50 even
 *     when the banner is hidden
 *
 * # Storage
 *
 *   localStorage key: `caelex-ai-disclosure-dismissed`
 *   value: ISO timestamp of dismissal
 *   read: parse → check `now - timestamp > 24h` → re-show if so
 *
 *   localStorage rather than cookies because (a) no server round-trip
 *   needed, (b) privacy: dismissal state never leaves the device, and
 *   (c) cookie-banner clutter is not what Art. 50 is asking for.
 */

const STORAGE_KEY = "caelex-ai-disclosure-dismissed";
const TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

export interface AIDisclosureBannerProps {
  /** Override copy — useful for embed surfaces (Pulse, Atlas)
   *  that may want regulator-specific wording. Defaults to the
   *  generic Comply V2 message. */
  message?: string;
  /** Override storage key — keep separate dismissal state for
   *  different surfaces if needed. */
  storageKey?: string;
}

export function AIDisclosureBanner({
  message,
  storageKey = STORAGE_KEY,
}: AIDisclosureBannerProps) {
  // Hidden until we've checked localStorage; flicker-free first paint.
  const [hidden, setHidden] = React.useState(true);

  React.useEffect(() => {
    try {
      const stored = window.localStorage.getItem(storageKey);
      if (!stored) {
        setHidden(false);
        return;
      }
      const dismissedAt = Date.parse(stored);
      if (Number.isFinite(dismissedAt) && Date.now() - dismissedAt < TTL_MS) {
        setHidden(true);
        return;
      }
      // Stale dismissal — re-show.
      setHidden(false);
    } catch {
      // localStorage unavailable (private browsing, SSR) — show banner
      // by default so the disclosure is never silently suppressed.
      setHidden(false);
    }
  }, [storageKey]);

  const dismiss = React.useCallback(() => {
    try {
      window.localStorage.setItem(storageKey, new Date().toISOString());
    } catch {
      // Best-effort persistence — banner still hides for the rest of
      // this mount even if storage failed.
    }
    setHidden(true);
  }, [storageKey]);

  if (hidden) return null;

  return (
    <div
      role="status"
      aria-label="AI assistant disclosure"
      data-testid="ai-disclosure-banner"
      className="mb-3 flex items-start gap-3 rounded-md border-l-2 border-amber-500/60 bg-amber-500/[0.05] p-3 ring-1 ring-inset ring-amber-500/20"
    >
      <Bot className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" />
      <div className="min-w-0 flex-1">
        <p className="text-[12px] font-medium text-amber-100">
          You're interacting with an AI system
        </p>
        <p className="mt-1 text-[11px] leading-relaxed text-amber-100/80">
          {message ??
            "Astra is an AI compliance copilot — not a human expert. Outputs are generated by Anthropic Claude and may contain errors, omissions, or hallucinations. Verify regulatory references with primary sources or qualified counsel before any submission to authorities. Per EU AI Act Art. 50, this disclosure is mandatory."}
        </p>
      </div>
      <button
        type="button"
        onClick={dismiss}
        aria-label="Dismiss disclosure for 24 hours"
        className="shrink-0 rounded p-1 text-amber-300/60 transition hover:bg-amber-500/10 hover:text-amber-200"
      >
        <X className="h-3 w-3" />
      </button>
    </div>
  );
}
