"use client";

import { useRef } from "react";
import { motion, useInView } from "framer-motion";

const fadeUp = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, ease: [0.25, 0.1, 0.25, 1] },
  },
};

const stagger = { visible: { transition: { staggerChildren: 0.08 } } };

function Section({
  children,
  className = "",
}: {
  children: React.ReactNode;
  className?: string;
}) {
  const ref = useRef(null);
  const inView = useInView(ref, { once: true, margin: "-60px" });
  return (
    <motion.div
      ref={ref}
      initial="hidden"
      animate={inView ? "visible" : "hidden"}
      variants={stagger}
      className={className}
    >
      {children}
    </motion.div>
  );
}

const ROWS = [
  { req: "Space Activity License", de: "BNetzA", no: "NOSA", gb: "CAA" },
  {
    req: "Debris Mitigation Plan",
    de: "Required",
    no: "Required",
    gb: "Required",
  },
  {
    req: "Liability Declaration",
    de: "SatDSiG",
    no: "Romvirksomhet",
    gb: "SIA 2018",
  },
  { req: "Frequency Authority", de: "BNetzA", no: "Nkom", gb: "Ofcom" },
  { req: "Approval Timeline", de: "8–12 mo", no: "6–9 mo", gb: "6–12 mo" },
];

const IMPACT = [
  {
    label: "Score Delta",
    primary: "82% → 79%",
    secondary: "3 new requirements unassessed",
  },
  {
    label: "New Documents",
    primary: "4 needed",
    secondary: "3 auto-generated by Caelex",
  },
  {
    label: "Approval Time",
    primary: "6–9 mo",
    secondary: "vs. 8–12 months (DE)",
  },
];

export default function JurisdictionSection() {
  return (
    <section className="py-24 md:py-36 bg-[#030712] border-t border-[#1F2937]">
      <div className="max-w-[720px] mx-auto px-6 md:px-12">
        <Section>
          <motion.p
            variants={fadeUp}
            className="text-[11px] font-mono uppercase tracking-[0.3em] text-[#4B5563] mb-4"
          >
            Jurisdiction Simulation
          </motion.p>

          <motion.h2
            variants={fadeUp}
            className="text-[clamp(1.5rem,3.5vw,2.5rem)] font-bold leading-[1.15] tracking-[-0.03em] text-[#F9FAFB] mb-6"
          >
            &ldquo;What changes if I launch from
            <br />
            Norway instead of Germany?&rdquo;
          </motion.h2>

          <motion.p
            variants={fadeUp}
            className="text-[15px] text-[#9CA3AF] leading-[1.75] mb-12"
          >
            Today, this question costs &euro;20,000–50,000 in legal fees and 4–6
            weeks of analysis. Per jurisdiction. Ephemeris answers it in seconds
            — because the regulatory knowledge base is already codified across 7
            European jurisdictions.
          </motion.p>
        </Section>

        {/* Comparison table */}
        <Section>
          <motion.div
            variants={fadeUp}
            className="overflow-x-auto rounded-xl border border-[#1F2937]"
          >
            <table className="w-full text-left font-mono text-[11px]">
              <thead>
                <tr className="border-b border-[#1F2937]">
                  <th className="px-4 py-3 text-[#6B7280] font-semibold uppercase tracking-[0.1em]">
                    Requirement
                  </th>
                  <th className="px-4 py-3 text-[#10B981] font-semibold uppercase tracking-[0.1em]">
                    DE
                  </th>
                  <th className="px-4 py-3 text-[#10B981] font-semibold uppercase tracking-[0.1em]">
                    NO
                  </th>
                  <th className="px-4 py-3 text-[#10B981] font-semibold uppercase tracking-[0.1em]">
                    GB
                  </th>
                </tr>
              </thead>
              <tbody>
                {ROWS.map((row) => (
                  <tr
                    key={row.req}
                    className="border-b border-[#1F2937] last:border-b-0"
                  >
                    <td className="px-4 py-3 text-[#9CA3AF]">{row.req}</td>
                    <td className="px-4 py-3 text-[#6B7280]">{row.de}</td>
                    <td className="px-4 py-3 text-[#6B7280]">{row.no}</td>
                    <td className="px-4 py-3 text-[#6B7280]">{row.gb}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </motion.div>
        </Section>

        {/* Impact cards */}
        <Section className="mt-8">
          <motion.div
            variants={fadeUp}
            className="grid grid-cols-1 sm:grid-cols-3 gap-3"
          >
            {IMPACT.map((item) => (
              <div
                key={item.label}
                className="rounded-lg p-4"
                style={{
                  background: "#0A0F1A",
                  border: "1px solid #1F2937",
                }}
              >
                <p className="font-mono text-[10px] uppercase tracking-[0.15em] text-[#4B5563] mb-2">
                  {item.label}
                </p>
                <p className="text-[16px] font-bold text-[#F9FAFB] mb-1">
                  {item.primary}
                </p>
                <p className="text-[12px] text-[#6B7280]">{item.secondary}</p>
              </div>
            ))}
          </motion.div>
        </Section>
      </div>
    </section>
  );
}
