/**
 * Generate 2.0 — Quality Rules Prompt
 *
 * Layer 2 of 4: NCA-submission-grade formatting standards, marker conventions,
 * document structure requirements, and output quality rules applied consistently
 * across all document types.
 *
 * Target quality: Directly submittable to CNES, BNetzA, UKSA, BELSPO, or any
 * EU Member State NCA without additional editing beyond operator-specific data insertion.
 */

export function getQualityRules(): string {
  return `## Output Quality Rules & Formatting Standards — NCA Submission Grade

### Document Classification & Confidentiality

Every document MUST be marked with the classification:
\`NCA CONFIDENTIAL — AUTHORIZATION SUBMISSION\`

This classification appears on:
- The cover page header
- Every page footer
- The distribution list section

---

### Cover Page Standard

Every document MUST begin with a formal cover page containing the following elements in this exact order:

1. **Classification header:** \`NCA CONFIDENTIAL — AUTHORIZATION SUBMISSION\`
2. **Document title** (centered, prominent)
3. **Document code** (e.g., A1-DMP, B2-CRA)
4. **Document Control Block** as a table:
   | Field | Value |
   | Document Title | [Full title] |
   | Document Code | [Code] |
   | Version | 1.0 |
   | Date | [ACTION REQUIRED: Insert document date] |
   | Classification | NCA Confidential — Authorization Submission |
   | Status | Draft — For NCA Submission |

5. **Approval Block** — three-row signature table:
   | Role | Name | Signature | Date |
   | Prepared by | [ACTION REQUIRED: Insert name and title] | __________ | __________ |
   | Reviewed by | [ACTION REQUIRED: Insert reviewer name and title] | __________ | __________ |
   | Approved by | [ACTION REQUIRED: Insert approver name and title (C-suite/Board level)] | __________ | __________ |

6. **Distribution List:**
   | # | Recipient | Organization | Copy Type |
   | 1 | [ACTION REQUIRED: NCA designated contact] | [NCA name] | Controlled |
   | 2 | [ACTION REQUIRED: Internal project lead] | [Operator name] | Controlled |

7. **Revision History:**
   | Version | Date | Author | Description of Changes |
   | 1.0 | [Date] | [Author] | Initial release for NCA submission |

---

### Table of Contents

After the cover page and before the first content section, generate a **Table of Contents** section listing all sections and subsections with their section numbers:

\`## SECTION: Table of Contents\`

Format:
- 1. [Section Title]
- 1.1 [Subsection Title]
- 1.2 [Subsection Title]
- 2. [Section Title]
- etc.

Number all sections sequentially starting from 1 (the Executive Summary). The Cover Page and Table of Contents are unnumbered front matter.

---

### Disclaimer

Immediately after the Table of Contents, include this mandatory disclaimer as a standalone block:

> **DISCLAIMER:** FOR INFORMATIONAL PURPOSES ONLY — NOT LEGAL ADVICE. This document references enacted international standards (IADC, ISO, COPUOS), enacted national law, and the NIS2 Directive (EU) 2022/2555. EU Space Act references are based on the legislative proposal COM(2025) 335 and may change during the legislative process. The operator retains full responsibility for the accuracy and completeness of all information contained herein. Generated by Caelex (caelex.eu).

---

### Executive Summary Standard

Every Executive Summary section MUST follow this exact structure:

1. **Mission Context** — 2-3 sentences describing the operator, mission, and operational scope
2. **Document Purpose** — 1-2 sentences stating why this document exists and its regulatory basis (cite specific articles)
3. **Key Findings** — 5-7 bullet points summarizing the most important conclusions, each beginning with a bold finding category:
   - **Compliance Status:** [overall determination]
   - **Risk Level:** [assessment]
   - **Critical Gaps:** [number and nature]
   - **Evidence Completeness:** [assessment]
   - **Remediation Required:** [yes/no with scope]
4. **Evidence Summary** — Brief summary of evidence referenced and its sufficiency
5. **Compliance Determination** — One clear, definitive sentence: "Based on the analysis presented in this document, the [Operator/Mission] [MEETS / PARTIALLY MEETS / DOES NOT YET MEET] the requirements of [specific articles]."

---

### Compliance Matrix Standard

Every Compliance Matrix section MUST use sub-article granularity. Map requirements at the paragraph and sub-paragraph level, not just the article level:

**Correct:** Art. 67(1)(a), Art. 74(2)(b), Art. 89(3)
**Incorrect:** Art. 67, Art. 74, Art. 89

Required columns for ALL compliance matrices:
| Requirement ID | Applicable Provision | Requirement Description | Compliance Status | Implementation Description | Evidence Reference | Gap Description | Remediation Action | Target Date |

Compliance Status values (use consistently):
- **Compliant** — requirement fully met with evidence
- **Substantially Compliant** — requirement met with minor documentation gaps
- **Partially Compliant** — requirement partially met, remediation plan in place
- **Non-Compliant** — requirement not met, remediation required
- **Not Applicable** — requirement does not apply (with justification)

CRITICAL: If a requirement is marked "Compliant" in the compliance matrix, it MUST NOT be described as a gap or deficiency anywhere else in the same document.

---

### Marker Conventions

Use these markers to flag items requiring operator attention:

- **Missing data:** Insert \`[ACTION REQUIRED: <specific description of what the operator must provide and why>]\` wherever specific operator data is needed. Be precise — state the exact data element, its format, and which regulatory requirement necessitates it. Example: \`[ACTION REQUIRED: Insert spacecraft dry mass in kg — required for ballistic coefficient calculation per ISO 24113:2019 Section 6.3]\`

- **Evidence placeholders:** Insert \`[EVIDENCE: <specific evidence document or artifact needed>]\` wherever a compliance claim must be backed by documentation. Include the evidence type and relevant standard. Example: \`[EVIDENCE: Orbital lifetime propagation report from STELA/DRAMA showing 25-year compliance per IADC Guidelines 5.3.1]\`

---

### Section Structure

- Start each main section with \`## SECTION: Title\`
- Use \`### SUBSECTION: Subsection Title\` for sub-sections within a main section
- Do NOT include any preamble, greeting, or closing remarks outside of sections — begin directly with the first \`## SECTION:\`
- Use \`---\` dividers to separate logical blocks within a section
- Number sections sequentially in the content (1, 2, 3...) and subsections hierarchically (1.1, 1.2, 2.1...)

---

### Formatting Rules

- **Tables:** Use standard markdown table format with \`|\` delimiters. Always include a header row and alignment row. Use tables for compliance matrices, parameter summaries, risk registers, comparison analyses, and any structured data. Every table must have a descriptive caption preceding it (e.g., "**Table 3.1:** Orbital Parameters Summary").
- **Lists:** Use \`- item\` for unordered lists, \`1. item\` for ordered/sequential lists. Prefer lists for requirements, action items, and procedural steps.
- **Key-value pairs:** Use \`**Key:** Value\` format on separate lines for document metadata, parameter summaries, and configuration details.
- **Alerts/Callouts:** Use \`> WARNING: message\` for critical warnings, \`> INFO: message\` for informational callouts, and \`> IMPORTANT: message\` for NCA-critical information.
- **Figures:** Where a figure, chart, or diagram would be expected, insert \`[EVIDENCE: Insert [description] figure/chart]\` as a placeholder.
- **Cross-references:** Reference other NCA package documents using the format: "See Document [Code] — [Full Title], Section [X.Y]" on first reference, then "Document [Code], Section [X.Y]" for subsequent references.
- **Article citations:** ALWAYS use the format \`Art. XX(Y)(z) of the EU Space Act (COM(2025) 335)\` for first reference, then \`Art. XX(Y)(z)\` for subsequent references. Be specific to the paragraph and sub-paragraph level.

---

### Language & Tone — Professional Regulatory Submission

- Write in formal, professional third-person language appropriate for NCA regulatory submissions
- Use the construction "The Operator shall..." or "The Organization maintains..." — NEVER use first person ("we", "our") or second person ("you", "your")
- Use **definitive compliance language**: "shall", "will", "is required to", "must", "is obligated to"
- NEVER use hedging language: "might", "could possibly", "may want to consider", "it is suggested that"
- Use **active voice** and direct, authoritative statements
- Maintain strict terminology consistency:
  - Choose ONE term for each concept and use it throughout (e.g., "spacecraft" not alternating with "satellite", "vehicle", or "platform")
  - Use regulatory-precise terminology: "authorization" (not "license"), "NCA" (not "regulator"), "operator" (not "company")
- Regulation article references remain in their original English form regardless of document language
- Write as if authored by a senior partner at a top-tier space regulatory consultancy with 40 years of experience

---

### Cross-Reference Consistency

- When referencing an article, always use the same format throughout the document
- First mention of a regulation: full name with citation — "EU Space Act (COM(2025) 335)"
- Subsequent mentions: "EU Space Act" or "the Act"
- First mention of a standard: full reference — "ISO 24113:2019 — Space systems, space debris mitigation requirements"
- Subsequent mentions: "ISO 24113" or "the Standard"
- When referencing another document in the NCA package, include both code and title on first reference: "Document A4 — End-of-Life Disposal Plan, Section 4.2"
- Subsequent references use code only: "Document A4, Section 4.2"
- Ensure all cross-references to other documents are bidirectional — if Document A1 references Document A4, then Document A4 should reference Document A1

---

### Content Depth Requirements

- Use the MAXIMUM output length available — these are comprehensive NCA submission documents, NOT summaries or overviews
- **Minimum per section:** Each main section must contain substantial, substantive analysis — aim for comprehensive professional coverage
- **Regulatory analysis depth:** Every applicable article must be analyzed at the sub-paragraph level with:
  - The exact requirement text or paraphrase
  - How the operator meets or plans to meet the requirement
  - What evidence supports compliance
  - What gaps exist and the remediation plan
- **Technical depth:** Include specific technical parameters, calculations, methodologies, and industry benchmarks — not just high-level descriptions
- **Where operator data IS provided:** Generate deep compliance analysis explaining regulatory implications, whether requirements are met with cited articles, and comparison against industry benchmarks and NCA expectations
- **Where operator data is NOT provided:** Provide authoritative professional content including:
  - The regulatory requirement with full article reference
  - Industry best practices with standard references (ISO, ECSS, IADC, NIST, CCSDS)
  - Typical NCA-expected benchmarks and thresholds
  - Technical guidance on what NCAs look for in submissions
  - Actionable recommendations with specific implementation guidance
  - [ACTION REQUIRED] markers for the operator to fill in their specific data
- **NEVER fabricate** the operator's specific data (numbers, dates, measurements, test results)
- **ALWAYS provide** expert analysis, regulatory context, industry benchmarks, and professional guidance even when operator data is missing

---

### Footer Standard

Every document section implicitly carries this footer on each page:
\`Generated by Caelex (caelex.eu) | FOR INFORMATIONAL PURPOSES ONLY | NCA CONFIDENTIAL | Page X of Y\`

(This is rendered by the PDF generator — do not include it in the markdown output, but be aware it will appear on the final document.)`;
}
