/**
 * Copyright 2026 Julian Polleschner (Caelex Einzelunternehmen). All rights reserved.
 *
 * generate-legal-sources-meta — bakes the client-safe corpus metadata
 * (Atlas perf pass F3).
 *
 * Reads the full legal-sources barrel (server-side, ~3MB) and writes
 * two LIGHT generated modules that client components may import:
 *
 *   src/data/legal-sources/meta.generated.ts         (~5KB)
 *     - CORPUS_STATS, JURISDICTION_CODES,
 *       SOURCE_JURISDICTION_CODES, JURISDICTION_META
 *
 *   src/data/legal-sources/source-meta.generated.ts  (~100KB)
 *     - SOURCE_META (id → jurisdiction/type/status/title_en records)
 *
 * Run after ANY corpus change (sources/*.ts):
 *
 *   npx tsx scripts/generate-legal-sources-meta.ts
 *
 * CI safety: src/data/legal-sources/meta-drift.test.ts re-derives the
 * meta from the corpus and fails if the committed artifacts are stale.
 *
 * SPDX-License-Identifier: LicenseRef-Caelex-Proprietary
 */

import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  buildLegalSourcesMeta,
  buildSourceMetaRecords,
} from "@/data/legal-sources/meta-builder";

/* Repo-root-relative, matching scripts/lint-legal-corpus.ts convention
 * (the documented invocation runs from the repo root). */
const OUT_DIR = join(process.cwd(), "src", "data", "legal-sources");

const GENERATED_HEADER = `/**
 * AUTO-GENERATED — DO NOT EDIT BY HAND.
 *
 * Generated by scripts/generate-legal-sources-meta.ts from the
 * legal-sources corpus barrel. Regenerate after any corpus change:
 *
 *   npx tsx scripts/generate-legal-sources-meta.ts
 *
 * Guarded by src/data/legal-sources/meta-drift.test.ts (CI fails if
 * this file is stale). Client-safe: contains ONLY light metadata, no
 * key_provisions / scope texts.
 *
 * SPDX-License-Identifier: LicenseRef-Caelex-Proprietary
 */
`;

function main(): void {
  const meta = buildLegalSourcesMeta();
  const sourceMeta = buildSourceMetaRecords();

  const metaFile = `${GENERATED_HEADER}
import type {
  CorpusStats,
  JurisdictionMetaRecord,
} from "./types";

/** Top-level corpus inventory counts. */
export const CORPUS_STATS: CorpusStats = ${JSON.stringify(meta.stats, null, 2)};

/** All catalogued jurisdiction codes (getAvailableJurisdictions order). */
export const JURISDICTION_CODES: readonly string[] = ${JSON.stringify(
    meta.jurisdictionCodes,
    null,
    2,
  )};

/** Distinct \`source.jurisdiction\` values across ALL_SOURCES, sorted. */
export const SOURCE_JURISDICTION_CODES: readonly string[] = ${JSON.stringify(
    meta.sourceJurisdictionCodes,
    null,
    2,
  )};

/** Per-jurisdiction aggregates (counts, treaty flags, quick-ref data). */
export const JURISDICTION_META: readonly JurisdictionMetaRecord[] = ${JSON.stringify(
    meta.jurisdictions,
    null,
    2,
  )};
`;

  /* Tuple encoding ([id, jurisdiction, type, status, title_en]) instead
   * of keyed objects: drops ~60 bytes of repeated keys per record from
   * the shipped bundle (~1.1k records). ./source-meta.ts re-inflates to
   * LegalSourceMetaRecord at module load. prettier-ignore keeps the
   * one-row-per-line layout stable across formatting runs. */
  const tupleRows = sourceMeta
    .map((s) =>
      JSON.stringify([s.id, s.jurisdiction, s.type, s.status, s.title_en]),
    )
    .join(",\n  ");

  const sourceMetaFile = `${GENERATED_HEADER}
import type { LegalSourceType, LegalSourceStatus } from "./types";

/** Row layout: [id, jurisdiction, type, status, title_en]. */
export type SourceMetaTuple = readonly [
  string,
  string,
  LegalSourceType,
  LegalSourceStatus,
  string,
];

/** Light per-source rows (see ./source-meta.ts for the record facade). */
// prettier-ignore
export const SOURCE_META_TUPLES: readonly SourceMetaTuple[] = [
  ${tupleRows},
];
`;

  const metaPath = join(OUT_DIR, "meta.generated.ts");
  const sourceMetaPath = join(OUT_DIR, "source-meta.generated.ts");

  writeFileSync(metaPath, metaFile, "utf8");
  writeFileSync(sourceMetaPath, sourceMetaFile, "utf8");

  // Normalise through prettier so the committed artifacts are stable
  // across regenerations (otherwise pre-commit formatting would churn
  // the diff every time the generator runs).
  execSync(
    `npx prettier --write "${metaPath}" "${sourceMetaPath}" --log-level=silent`,
    { stdio: "inherit" },
  );

  console.log(
    `✓ meta.generated.ts          ${meta.jurisdictions.length} jurisdictions, ` +
      `${meta.stats.sources} sources, ${meta.stats.authorities} authorities`,
  );
  console.log(`✓ source-meta.generated.ts   ${sourceMeta.length} records`);
}

main();
