/**
 * Audit Center Report PDF Template
 * Comprehensive cross-module compliance report with evidence register,
 * gap analysis, hash chain statement, and certification.
 */

import React from "react";
import { BaseReport } from "../templates/base-report";
import type {
  ReportConfig,
  ReportSection,
  ReportSectionContent,
} from "../types";

export interface AuditCenterReportData {
  organizationName: string;
  generatedAt: Date;
  generatedBy: string;
  period: { from: Date; to: Date };
  complianceScore: number;
  modules: Array<{
    name: string;
    regulationType: string;
    totalRequirements: number;
    compliant: number;
    partial: number;
    nonCompliant: number;
    notAssessed: number;
    score: number;
  }>;
  evidenceRegister: Array<{
    title: string;
    regulationType: string;
    requirementId: string;
    evidenceType: string;
    status: string;
    documentCount: number;
    validFrom?: string | null;
    validUntil?: string | null;
  }>;
  gapAnalysis: Array<{
    regulationType: string;
    requirementId: string;
    title: string;
    status: string;
    severity: string;
  }>;
  hashChain: {
    valid: boolean;
    checkedEntries: number;
    brokenAt?: string | null;
  };
  auditTrailSample: Array<{
    timestamp: string;
    user: string;
    action: string;
    entityType: string;
    description?: string | null;
  }>;
}

function formatDate(date: Date): string {
  return date.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
}

function buildReportConfig(data: AuditCenterReportData): ReportConfig {
  const sections: ReportSection[] = [];

  // Section 1: Executive Summary
  const summaryContent: ReportSectionContent[] = [
    {
      type: "text",
      value: `This Audit Center Report provides a comprehensive overview of ${data.organizationName}'s regulatory compliance posture across all applicable frameworks. The report covers the period from ${formatDate(data.period.from)} to ${formatDate(data.period.to)}.`,
    },
    { type: "spacer", height: 10 },
    {
      type: "keyValue",
      items: [
        { key: "Organization", value: data.organizationName },
        { key: "Overall Compliance Score", value: `${data.complianceScore}%` },
        { key: "Modules Assessed", value: `${data.modules.length}` },
        { key: "Evidence Items", value: `${data.evidenceRegister.length}` },
        { key: "Outstanding Gaps", value: `${data.gapAnalysis.length}` },
        {
          key: "Audit Trail Integrity",
          value: data.hashChain.valid
            ? "VERIFIED"
            : "BROKEN - Investigation Required",
        },
        { key: "Report Generated", value: formatDate(data.generatedAt) },
        { key: "Generated By", value: data.generatedBy },
      ],
    },
  ];
  sections.push({ title: "1. Executive Summary", content: summaryContent });

  // Section 2: Compliance Matrix
  const matrixContent: ReportSectionContent[] = [
    {
      type: "text",
      value:
        "The following table summarizes compliance status across all regulatory modules:",
    },
    { type: "spacer", height: 5 },
    {
      type: "table",
      headers: [
        "Module",
        "Total Reqs",
        "Compliant",
        "Partial",
        "Non-Compliant",
        "Not Assessed",
        "Score",
      ],
      rows: data.modules.map((m) => [
        m.name,
        String(m.totalRequirements),
        String(m.compliant),
        String(m.partial),
        String(m.nonCompliant),
        String(m.notAssessed),
        `${m.score}%`,
      ]),
    },
  ];
  sections.push({ title: "2. Compliance Matrix", content: matrixContent });

  // Section 3: Evidence Register
  if (data.evidenceRegister.length > 0) {
    const evidenceContent: ReportSectionContent[] = [
      {
        type: "text",
        value: `A total of ${data.evidenceRegister.length} evidence items have been registered against specific compliance requirements:`,
      },
      { type: "spacer", height: 5 },
      {
        type: "table",
        headers: [
          "Title",
          "Regulation",
          "Type",
          "Status",
          "Documents",
          "Valid Until",
        ],
        rows: data.evidenceRegister.map((ev) => [
          ev.title,
          ev.regulationType.replace(/_/g, " "),
          ev.evidenceType.replace(/_/g, " "),
          ev.status,
          String(ev.documentCount),
          ev.validUntil || "N/A",
        ]),
      },
    ];
    sections.push({ title: "3. Evidence Register", content: evidenceContent });
  }

  // Section 4: Gap Analysis
  if (data.gapAnalysis.length > 0) {
    const gapContent: ReportSectionContent[] = [
      {
        type: "text",
        value: `The following ${data.gapAnalysis.length} compliance gaps have been identified and require remediation:`,
      },
      { type: "spacer", height: 5 },
      {
        type: "table",
        headers: ["Regulation", "Requirement", "Title", "Status", "Severity"],
        rows: data.gapAnalysis
          .slice(0, 50)
          .map((gap) => [
            gap.regulationType.replace(/_/g, " "),
            gap.requirementId,
            gap.title.length > 40 ? gap.title.slice(0, 40) + "..." : gap.title,
            gap.status.replace(/_/g, " "),
            gap.severity,
          ]),
      },
    ];
    if (data.gapAnalysis.length > 50) {
      gapContent.push({
        type: "text",
        value: `... and ${data.gapAnalysis.length - 50} additional gaps. See the full audit package for complete details.`,
      });
    }
    sections.push({ title: "4. Gap Analysis", content: gapContent });
  }

  // Section 5: Hash Chain Statement
  const hashContent: ReportSectionContent[] = [
    {
      type: "text",
      value:
        "All audit trail entries are cryptographically chained using SHA-256 hashes. Each entry's hash includes the previous entry's hash, creating a tamper-evident chain that can detect unauthorized modifications.",
    },
    { type: "spacer", height: 5 },
    {
      type: "keyValue",
      items: [
        {
          key: "Chain Status",
          value: data.hashChain.valid
            ? "VALID - No tampering detected"
            : "BROKEN - Tampering detected",
        },
        {
          key: "Entries Verified",
          value: String(data.hashChain.checkedEntries),
        },
        ...(data.hashChain.brokenAt
          ? [{ key: "Break Point", value: data.hashChain.brokenAt }]
          : []),
      ],
    },
  ];
  if (!data.hashChain.valid) {
    hashContent.push({
      type: "alert",
      severity: "error",
      message:
        "INTEGRITY WARNING: The audit hash chain has been broken. This may indicate unauthorized modification of audit records. An investigation is strongly recommended.",
    });
  }
  sections.push({
    title: "5. Hash Chain Integrity Statement",
    content: hashContent,
  });

  // Section 6: Audit Trail Sample
  if (data.auditTrailSample.length > 0) {
    const trailContent: ReportSectionContent[] = [
      {
        type: "text",
        value: `Recent audit trail activity (last ${data.auditTrailSample.length} entries):`,
      },
      { type: "spacer", height: 5 },
      {
        type: "table",
        headers: ["Timestamp", "User", "Action", "Entity", "Description"],
        rows: data.auditTrailSample.map((entry) => [
          entry.timestamp,
          entry.user,
          entry.action.replace(/_/g, " "),
          entry.entityType.replace(/_/g, " "),
          entry.description
            ? entry.description.length > 50
              ? entry.description.slice(0, 50) + "..."
              : entry.description
            : "",
        ]),
      },
    ];
    sections.push({ title: "6. Audit Trail Sample", content: trailContent });
  }

  // Section 7: Certification
  const certContent: ReportSectionContent[] = [
    {
      type: "text",
      value: `This report has been generated automatically by the Caelex Compliance Platform for ${data.organizationName}. The data contained herein reflects the compliance status as of ${formatDate(data.generatedAt)}.`,
    },
    { type: "spacer", height: 10 },
    {
      type: "text",
      value:
        "This document is intended for internal compliance management and regulatory audit purposes. It does not constitute legal advice or a guarantee of regulatory approval.",
    },
    { type: "spacer", height: 10 },
    {
      type: "keyValue",
      items: [
        { key: "Document Type", value: "Audit Center Compliance Report" },
        {
          key: "Applicable Frameworks",
          value: data.modules.map((m) => m.name).join(", "),
        },
        {
          key: "Hash Chain Verified",
          value: data.hashChain.valid ? "Yes" : "No - see Section 5",
        },
      ],
    },
  ];
  sections.push({ title: "7. Certification", content: certContent });

  return {
    metadata: {
      reportId: `ACR-${Date.now()}`,
      reportType: "audit_center",
      title: "Audit Center Compliance Report",
      generatedAt: data.generatedAt,
      generatedBy: data.generatedBy,
      organization: data.organizationName,
      version: "1.0",
    },
    header: {
      title: "Audit Center Compliance Report",
      subtitle: data.organizationName,
      reportNumber: `ACR-${data.generatedAt.getFullYear()}-${String(data.generatedAt.getMonth() + 1).padStart(2, "0")}`,
      date: data.generatedAt,
      logo: true,
    },
    footer: {
      pageNumbers: true,
      confidentialityNotice:
        "CONFIDENTIAL - For authorized compliance personnel only",
      disclaimer:
        "Generated by Caelex Compliance Platform. This report does not constitute legal advice.",
    },
    sections,
  };
}

export function AuditCenterReport({ data }: { data: AuditCenterReportData }) {
  const config = buildReportConfig(data);
  return <BaseReport config={config} />;
}
