"use client";

/**
 * AIBadge — the violet "AI" chip required by EU AI Act Article 50.
 *
 * Fulfills the "MUST-IMPLEMENT" checklist item #1 from the brief:
 * "violet --ai-9 chip at top; click reveals model name + version +
 *  knowledge cutoff."
 *
 * Click opens a Popover with model card info. The popover content is
 * intentionally terse — deep compliance info lives in the full Model
 * Card page linked from the footer.
 *
 * No emoji. No sparkles icon. Just the letters "AI" in violet, matching
 * Copilot / Cursor / Notion AI convention.
 */

import { Popover, PopoverContent, PopoverTrigger } from "./primitives/Popover";
import { cn } from "@/lib/transparency/cn";

export interface AIBadgeProps {
  /** Model identifier — shown in the popover + optionally the chip. */
  model: string;
  /** ISO date / year-month string — "Training data cutoff: 2024-10". */
  cutoff?: string;
  /** If true, the chip expands to show model + cutoff inline. Default false. */
  expanded?: boolean;
  className?: string;
}

export function AIBadge({
  model,
  cutoff,
  expanded = false,
  className,
}: AIBadgeProps) {
  return (
    <Popover>
      <PopoverTrigger asChild>
        <button
          type="button"
          aria-label={`Generated by AI — ${model}${cutoff ? `, training cutoff ${cutoff}` : ""}. Click for details.`}
          className={cn(
            "inline-flex items-center gap-1 rounded-[--tp-radius-xs] px-1.5 py-0.5",
            "text-[11px] font-medium tracking-[0.02em]",
            "bg-[--ai-9] text-white",
            "hover:brightness-110 transition-[filter] duration-[--tp-dur-fast] ease-[--tp-ease-hover]",
            "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[--ai-9] focus-visible:ring-offset-1 focus-visible:ring-offset-[--n-1]",
            className,
          )}
        >
          <span aria-hidden>AI</span>
          {expanded && (
            <>
              <span className="opacity-70">·</span>
              <span className="font-normal opacity-90">{model}</span>
            </>
          )}
        </button>
      </PopoverTrigger>
      <PopoverContent
        align="start"
        className="w-72 p-4 space-y-2 bg-[--n-2] border border-[--n-6] shadow-[--tp-shadow-popover] rounded-[--tp-radius-lg]"
      >
        <div className="flex items-center gap-1.5 text-[11px] font-medium tracking-[0.02em]">
          <span className="inline-block px-1.5 py-0.5 rounded-[--tp-radius-xs] bg-[--ai-9] text-white">
            AI
          </span>
          <span className="text-[--n-11]">Generated by a language model</span>
        </div>
        <dl className="space-y-1 text-[13px]">
          <div className="flex justify-between gap-4">
            <dt className="text-[--n-11]">Model</dt>
            <dd className="font-[family-name:--tp-font-mono] text-[12px] text-[--n-12]">
              {model}
            </dd>
          </div>
          {cutoff && (
            <div className="flex justify-between gap-4">
              <dt className="text-[--n-11]">Cutoff</dt>
              <dd className="font-[family-name:--tp-font-mono] text-[12px] text-[--n-12]">
                {cutoff}
              </dd>
            </div>
          )}
        </dl>
        <p className="pt-2 border-t border-[--n-6] text-[12px] text-[--n-11] leading-relaxed">
          This answer is AI-generated and may contain inaccuracies. Verify
          against the cited sources before acting.
        </p>
      </PopoverContent>
    </Popover>
  );
}

export default AIBadge;
