// Timeline & Deadlines Module - Data Definitions
// Reference: EU Space Act compliance deadlines and regulatory requirements

import type { DeadlineCategory, Priority, ModuleType } from "@prisma/client";

// ============================================
// AUTO-GENERATED DEADLINE TEMPLATES
// ============================================

export interface DeadlineTemplate {
  trigger: string;
  title: string;
  description?: string;
  offsetDays?: number; // Negative = before trigger date, positive = after
  recurrence?: string; // RRULE format
  category: DeadlineCategory;
  priority: Priority;
  regulatoryRef?: string;
  penaltyInfo?: string;
  reminderDays?: number[];
}

export const autoGeneratedDeadlines: Record<ModuleType, DeadlineTemplate[]> = {
  AUTHORIZATION: [
    {
      trigger: "license_issued",
      title: "License Renewal Application",
      description: "Submit license renewal application before expiration",
      offsetDays: -90,
      category: "LICENSE",
      priority: "CRITICAL",
      regulatoryRef: "EU Space Act Art. 7",
      penaltyInfo:
        "License expiration leads to immediate cessation of operations",
      reminderDays: [90, 60, 30, 14, 7],
    },
    {
      trigger: "license_issued",
      title: "Annual License Compliance Review",
      description: "Conduct annual review of license compliance status",
      recurrence: "FREQ=YEARLY;BYMONTH=1;BYMONTHDAY=15",
      category: "REGULATORY",
      priority: "HIGH",
      regulatoryRef: "EU Space Act Art. 8",
    },
    {
      trigger: "authorization_granted",
      title: "Post-Authorization Documentation Update",
      description:
        "Update all authorization documentation within 30 days of approval",
      offsetDays: 30,
      category: "REGULATORY",
      priority: "HIGH",
      regulatoryRef: "EU Space Act Art. 9",
    },
  ],

  DEBRIS: [
    {
      trigger: "mission_created",
      title: "Debris Mitigation Plan Update",
      description: "Annual review and update of debris mitigation plan",
      recurrence: "FREQ=YEARLY",
      category: "REGULATORY",
      priority: "HIGH",
      regulatoryRef: "EU Space Act Art. 25-27",
    },
    {
      trigger: "satellite_eol_approaching",
      title: "Deorbit Plan Submission",
      description: "Submit detailed deorbit/disposal plan to NCA",
      offsetDays: -180,
      category: "REGULATORY",
      priority: "CRITICAL",
      regulatoryRef: "EU Space Act Art. 28",
      penaltyInfo:
        "Non-compliance may result in up to 2% annual turnover penalty",
    },
    {
      trigger: "mission_created",
      title: "Collision Avoidance Procedure Review",
      description: "Review and update collision avoidance procedures",
      recurrence: "FREQ=MONTHLY",
      category: "MISSION",
      priority: "HIGH",
      regulatoryRef: "EU Space Act Art. 26",
    },
  ],

  INSURANCE: [
    {
      trigger: "policy_created",
      title: "Insurance Policy Renewal",
      description: "Renew third-party liability insurance before expiration",
      offsetDays: -60,
      category: "INSURANCE",
      priority: "CRITICAL",
      regulatoryRef: "EU Space Act Art. 18",
      penaltyInfo: "Operations without valid insurance are prohibited",
      reminderDays: [60, 45, 30, 14, 7],
    },
    {
      trigger: "policy_created",
      title: "Insurance Certificate to NCA",
      description:
        "Submit updated insurance certificate to national competent authority",
      offsetDays: -30,
      category: "REPORTING",
      priority: "HIGH",
      regulatoryRef: "EU Space Act Art. 18",
    },
    {
      trigger: "policy_created",
      title: "Annual Insurance Coverage Review",
      description: "Review insurance coverage adequacy for current operations",
      recurrence: "FREQ=YEARLY",
      category: "INSURANCE",
      priority: "MEDIUM",
    },
  ],

  CYBERSECURITY: [
    {
      trigger: "assessment_completed",
      title: "Security Audit",
      description: "Conduct annual cybersecurity audit per NIS2 requirements",
      recurrence: "FREQ=YEARLY",
      category: "CERTIFICATION",
      priority: "HIGH",
      regulatoryRef: "NIS2 Directive",
    },
    {
      trigger: "incident_reported",
      title: "Incident Follow-up Report",
      description: "Submit detailed incident follow-up report",
      offsetDays: 30,
      category: "REPORTING",
      priority: "HIGH",
      regulatoryRef: "NIS2 Directive Art. 23",
    },
    {
      trigger: "assessment_completed",
      title: "Vulnerability Assessment",
      description: "Conduct quarterly vulnerability assessment",
      recurrence: "FREQ=QUARTERLY",
      category: "CERTIFICATION",
      priority: "MEDIUM",
    },
    {
      trigger: "assessment_completed",
      title: "Penetration Testing",
      description: "Conduct annual penetration testing of space systems",
      recurrence: "FREQ=YEARLY",
      category: "CERTIFICATION",
      priority: "HIGH",
      regulatoryRef: "EU Space Act Art. 74-95",
    },
  ],

  ENVIRONMENTAL: [
    {
      trigger: "mission_created",
      title: "Annual Environmental Report",
      description: "Submit annual environmental impact report",
      recurrence: "FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=31",
      category: "REPORTING",
      priority: "MEDIUM",
      regulatoryRef: "EU Space Act Art. 96-100",
    },
    {
      trigger: "mission_created",
      title: "Carbon Footprint Assessment Update",
      description: "Update carbon footprint assessment for space operations",
      recurrence: "FREQ=YEARLY",
      category: "INTERNAL",
      priority: "MEDIUM",
    },
    {
      trigger: "mission_created",
      title: "Environmental Footprint Declaration (EFD)",
      description: "Submit Environmental Footprint Declaration to EUSPA",
      recurrence: "FREQ=YEARLY;BYMONTH=6;BYMONTHDAY=30",
      category: "REGULATORY",
      priority: "HIGH",
      regulatoryRef: "EU Space Act Art. 97",
    },
  ],

  SUPERVISION: [
    {
      trigger: "nca_registered",
      title: "Quarterly Status Report",
      description: "Submit quarterly operational status report to NCA",
      recurrence: "FREQ=QUARTERLY",
      category: "REPORTING",
      priority: "HIGH",
      regulatoryRef: "EU Space Act Art. 45",
    },
    {
      trigger: "nca_registered",
      title: "Annual Compliance Report",
      description: "Submit comprehensive annual compliance report",
      recurrence: "FREQ=YEARLY;BYMONTH=3;BYMONTHDAY=31",
      category: "REGULATORY",
      priority: "CRITICAL",
      regulatoryRef: "EU Space Act Art. 45",
      penaltyInfo: "Non-submission may result in authorization suspension",
    },
    {
      trigger: "nca_registered",
      title: "NCA Inspection Preparation",
      description: "Prepare documentation for potential NCA inspection",
      recurrence: "FREQ=YEARLY",
      category: "INTERNAL",
      priority: "MEDIUM",
    },
  ],

  REGISTRATION: [
    {
      trigger: "asset_registered",
      title: "Registration Data Update",
      description: "Update registration data for any operational changes",
      recurrence: "FREQ=YEARLY",
      category: "REGULATORY",
      priority: "MEDIUM",
      regulatoryRef: "UN Registration Convention",
    },
    {
      trigger: "launch_completed",
      title: "UN Space Object Registration",
      description: "Register space object with UN registry",
      offsetDays: 60,
      category: "REGULATORY",
      priority: "CRITICAL",
      regulatoryRef: "Registration Convention Art. IV",
    },
  ],

  TIMELINE: [],
};

// ============================================
// REGULATORY DEADLINES (EU Space Act)
// ============================================

export interface RegulatoryDeadline {
  id: string;
  title: string;
  description: string;
  dueDate?: { month: number; day: number }; // Annual recurring
  offsetAfterLaunch?: number; // Days after launch
  offsetBeforeLaunch?: number; // Days before launch
  recurrence?: string;
  category: DeadlineCategory;
  priority: Priority;
  regulatoryRef: string;
  applicableTo: string[]; // Operator types or 'ALL'
  penaltyInfo?: string;
}

export const regulatoryDeadlines: RegulatoryDeadline[] = [
  {
    id: "esa-annual",
    title: "ESA Annual Report Submission",
    description: "Submit annual activity report to ESA",
    dueDate: { month: 2, day: 28 },
    category: "REGULATORY",
    priority: "HIGH",
    regulatoryRef: "ESA Convention Art. XI",
    applicableTo: ["ALL"],
  },
  {
    id: "un-registration",
    title: "UN Space Object Registration",
    description:
      "Register new space objects with UN registry within 60 days of launch",
    offsetAfterLaunch: 60,
    category: "REGULATORY",
    priority: "CRITICAL",
    regulatoryRef: "Registration Convention Art. IV",
    applicableTo: ["SCO", "LO"],
    penaltyInfo: "Failure to register may void liability protections",
  },
  {
    id: "itu-filing",
    title: "ITU Frequency Filing Deadline",
    description: "Submit frequency coordination filing to ITU",
    offsetBeforeLaunch: -365,
    category: "REGULATORY",
    priority: "CRITICAL",
    regulatoryRef: "ITU Radio Regulations",
    applicableTo: ["SCO"],
    penaltyInfo: "Late filing may result in frequency interference issues",
  },
  {
    id: "copernicus-data",
    title: "Copernicus Data Submission",
    description: "Quarterly data delivery to Copernicus program",
    recurrence: "FREQ=QUARTERLY",
    category: "CONTRACTUAL",
    priority: "MEDIUM",
    regulatoryRef: "Copernicus Regulation",
    applicableTo: ["EO_MISSION"],
  },
  {
    id: "galileo-prs",
    title: "Galileo PRS Compliance Report",
    description: "Submit Public Regulated Service compliance report",
    recurrence: "FREQ=YEARLY;BYMONTH=6;BYMONTHDAY=30",
    category: "REGULATORY",
    priority: "HIGH",
    regulatoryRef: "EU Space Act Art. 50-54",
    applicableTo: ["PRS_USER"],
  },
  {
    id: "ssa-data-sharing",
    title: "SSA Data Sharing Report",
    description:
      "Submit Space Situational Awareness data sharing compliance report",
    recurrence: "FREQ=YEARLY",
    category: "REGULATORY",
    priority: "MEDIUM",
    regulatoryRef: "EU Space Act Art. 55-60",
    applicableTo: ["SCO"],
  },
  {
    id: "eol-notification",
    title: "End-of-Life Notification",
    description: "Notify NCA of planned end-of-life operations",
    offsetAfterLaunch: -365, // Actually before EOL
    category: "REGULATORY",
    priority: "CRITICAL",
    regulatoryRef: "EU Space Act Art. 28",
    applicableTo: ["SCO"],
    penaltyInfo: "Non-compliance may result in significant penalties",
  },
];

// ============================================
// DEADLINE COLORS & DISPLAY
// ============================================

export const deadlineColors = {
  // Status colors
  status: {
    OVERDUE: "#ef4444", // Red
    DUE_SOON: "#f97316", // Orange (< 7 days)
    UPCOMING: "#eab308", // Yellow (< 30 days)
    ON_TRACK: "#22c55e", // Green
    COMPLETED: "#6b7280", // Gray
    CANCELLED: "#9ca3af", // Light gray
    EXTENDED: "#3b82f6", // Blue
  },

  // Category colors
  category: {
    REGULATORY: "#8b5cf6", // Violet
    LICENSE: "#3b82f6", // Blue
    REPORTING: "#06b6d4", // Cyan
    INSURANCE: "#10b981", // Emerald
    CERTIFICATION: "#f59e0b", // Amber
    MISSION: "#ec4899", // Pink
    INTERNAL: "#6b7280", // Gray
    CONTRACTUAL: "#84cc16", // Lime
  },

  // Priority colors
  priority: {
    CRITICAL: "#ef4444", // Red
    HIGH: "#f97316", // Orange
    MEDIUM: "#eab308", // Yellow
    LOW: "#22c55e", // Green
  },
};

// ============================================
// CATEGORY METADATA
// ============================================

export interface CategoryMeta {
  id: DeadlineCategory;
  label: string;
  description: string;
  icon: string;
  color: string;
}

export const categoryMetadata: CategoryMeta[] = [
  {
    id: "REGULATORY",
    label: "Regulatory",
    description: "Government and authority deadlines",
    icon: "Building2",
    color: deadlineColors.category.REGULATORY,
  },
  {
    id: "LICENSE",
    label: "License",
    description: "License and permit deadlines",
    icon: "FileCheck",
    color: deadlineColors.category.LICENSE,
  },
  {
    id: "REPORTING",
    label: "Reporting",
    description: "Report submission deadlines",
    icon: "FileText",
    color: deadlineColors.category.REPORTING,
  },
  {
    id: "INSURANCE",
    label: "Insurance",
    description: "Insurance policy deadlines",
    icon: "Shield",
    color: deadlineColors.category.INSURANCE,
  },
  {
    id: "CERTIFICATION",
    label: "Certification",
    description: "Certification and audit deadlines",
    icon: "Award",
    color: deadlineColors.category.CERTIFICATION,
  },
  {
    id: "MISSION",
    label: "Mission",
    description: "Mission-related deadlines",
    icon: "Rocket",
    color: deadlineColors.category.MISSION,
  },
  {
    id: "INTERNAL",
    label: "Internal",
    description: "Internal organizational deadlines",
    icon: "Users",
    color: deadlineColors.category.INTERNAL,
  },
  {
    id: "CONTRACTUAL",
    label: "Contractual",
    description: "Contractual obligation deadlines",
    icon: "FileSignature",
    color: deadlineColors.category.CONTRACTUAL,
  },
];

// ============================================
// HELPER FUNCTIONS
// ============================================

export function getStatusColor(status: string): string {
  return (
    deadlineColors.status[status as keyof typeof deadlineColors.status] ||
    "#6b7280"
  );
}

export function getCategoryColor(category: string): string {
  return (
    deadlineColors.category[category as keyof typeof deadlineColors.category] ||
    "#6b7280"
  );
}

export function getPriorityColor(priority: string): string {
  return (
    deadlineColors.priority[priority as keyof typeof deadlineColors.priority] ||
    "#6b7280"
  );
}

export function getDaysUntilDue(dueDate: Date): number {
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  const due = new Date(dueDate);
  due.setHours(0, 0, 0, 0);
  return Math.ceil((due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
}

export function getDeadlineUrgency(
  dueDate: Date,
): "overdue" | "due_soon" | "upcoming" | "on_track" {
  const days = getDaysUntilDue(dueDate);
  if (days < 0) return "overdue";
  if (days <= 7) return "due_soon";
  if (days <= 30) return "upcoming";
  return "on_track";
}

// ============================================
// MISSION PHASE DEFAULTS
// ============================================

export interface MissionPhaseTemplate {
  name: string;
  description: string;
  defaultDurationMonths: number;
  color: string;
  defaultMilestones: {
    name: string;
    offsetMonths: number;
    isCritical: boolean;
    isRegulatory: boolean;
    regulatoryRef?: string;
    icon?: string;
  }[];
}

export const missionPhaseTemplates: MissionPhaseTemplate[] = [
  {
    name: "Phase 0: Mission Analysis",
    description: "Initial mission concept and feasibility studies",
    defaultDurationMonths: 6,
    color: "#8b5cf6",
    defaultMilestones: [
      {
        name: "Mission Concept Review (MCR)",
        offsetMonths: 6,
        isCritical: true,
        isRegulatory: false,
        icon: "clipboard-check",
      },
    ],
  },
  {
    name: "Phase A: Feasibility",
    description: "Detailed feasibility study and preliminary design",
    defaultDurationMonths: 12,
    color: "#3b82f6",
    defaultMilestones: [
      {
        name: "Preliminary Requirements Review (PRR)",
        offsetMonths: 6,
        isCritical: false,
        isRegulatory: false,
      },
      {
        name: "System Requirements Review (SRR)",
        offsetMonths: 12,
        isCritical: true,
        isRegulatory: false,
        icon: "file-check",
      },
    ],
  },
  {
    name: "Phase B: Definition",
    description: "Detailed design and technology development",
    defaultDurationMonths: 18,
    color: "#06b6d4",
    defaultMilestones: [
      {
        name: "Preliminary Design Review (PDR)",
        offsetMonths: 12,
        isCritical: true,
        isRegulatory: false,
        icon: "drafting-compass",
      },
      {
        name: "Critical Design Review (CDR)",
        offsetMonths: 18,
        isCritical: true,
        isRegulatory: false,
        icon: "check-circle",
      },
      {
        name: "Authorization Application",
        offsetMonths: 15,
        isCritical: true,
        isRegulatory: true,
        regulatoryRef: "EU Space Act Art. 6-10",
        icon: "file-signature",
      },
    ],
  },
  {
    name: "Phase C: Manufacturing",
    description: "Flight model manufacturing and assembly",
    defaultDurationMonths: 24,
    color: "#10b981",
    defaultMilestones: [
      {
        name: "Manufacturing Readiness Review (MRR)",
        offsetMonths: 6,
        isCritical: false,
        isRegulatory: false,
      },
      {
        name: "Flight Model Complete",
        offsetMonths: 18,
        isCritical: true,
        isRegulatory: false,
        icon: "box",
      },
      {
        name: "Test Readiness Review (TRR)",
        offsetMonths: 20,
        isCritical: false,
        isRegulatory: false,
      },
      {
        name: "Insurance Policy Secured",
        offsetMonths: 22,
        isCritical: true,
        isRegulatory: true,
        regulatoryRef: "EU Space Act Art. 18",
        icon: "shield",
      },
    ],
  },
  {
    name: "Phase D: Qualification & Testing",
    description: "Environmental testing and qualification",
    defaultDurationMonths: 12,
    color: "#f59e0b",
    defaultMilestones: [
      {
        name: "Environmental Testing Complete",
        offsetMonths: 8,
        isCritical: true,
        isRegulatory: false,
        icon: "thermometer",
      },
      {
        name: "Qualification Review (QR)",
        offsetMonths: 10,
        isCritical: true,
        isRegulatory: false,
      },
      {
        name: "Flight Readiness Review (FRR)",
        offsetMonths: 12,
        isCritical: true,
        isRegulatory: false,
        icon: "rocket",
      },
      {
        name: "Authorization Received",
        offsetMonths: 11,
        isCritical: true,
        isRegulatory: true,
        regulatoryRef: "EU Space Act Art. 7",
        icon: "award",
      },
    ],
  },
  {
    name: "Phase E: Launch & Operations",
    description: "Launch campaign and mission operations",
    defaultDurationMonths: 60,
    color: "#ec4899",
    defaultMilestones: [
      {
        name: "Launch",
        offsetMonths: 0,
        isCritical: true,
        isRegulatory: false,
        icon: "rocket",
      },
      {
        name: "In-Orbit Testing (IOT) Complete",
        offsetMonths: 3,
        isCritical: true,
        isRegulatory: false,
      },
      {
        name: "Operational Acceptance",
        offsetMonths: 6,
        isCritical: true,
        isRegulatory: false,
        icon: "check-circle",
      },
      {
        name: "UN Registration",
        offsetMonths: 2,
        isCritical: true,
        isRegulatory: true,
        regulatoryRef: "Registration Convention Art. IV",
        icon: "globe",
      },
    ],
  },
  {
    name: "Phase F: Disposal",
    description: "End-of-life and decommissioning",
    defaultDurationMonths: 6,
    color: "#6b7280",
    defaultMilestones: [
      {
        name: "Deorbit Plan Submission",
        offsetMonths: -6,
        isCritical: true,
        isRegulatory: true,
        regulatoryRef: "EU Space Act Art. 28",
        icon: "file-text",
      },
      {
        name: "Passivation Complete",
        offsetMonths: 3,
        isCritical: true,
        isRegulatory: true,
        regulatoryRef: "EU Space Act Art. 27",
        icon: "power-off",
      },
      {
        name: "Disposal Complete",
        offsetMonths: 6,
        isCritical: true,
        isRegulatory: true,
        regulatoryRef: "EU Space Act Art. 28",
        icon: "check-circle",
      },
    ],
  },
];
